import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/db/storage';
import {z} from 'zod';
export const dynamic='force-dynamic';
const text=z.string().max(3000);
const schema=z.object({applications:z.array(z.object({id:z.string().uuid(),company:z.string().trim().min(1).max(120),role:z.string().trim().min(1).max(180),url:z.string().max(2000).refine(v=>!v||/^https?:\/\//.test(v)),status:z.enum(['Saved','Applied','Interviewing','Offer','Rejected']),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),notes:text})).max(1000),projects:z.array(text).max(100),courses:z.array(text).max(500),college:z.enum(['Rutgers–New Brunswick']),submissions:z.array(z.object({id:z.string().uuid(),problem:z.string().max(100),passed:z.number().int().min(0).max(100),total:z.number().int().min(1).max(100),code:z.string().max(20000),date:z.string().max(40)})).max(200)});
const empty={applications:[],projects:[],courses:[],college:'Rutgers–New Brunswick',submissions:[]};
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({user:null,state:empty});try{const row=await database().prepare('SELECT data, plan FROM workspaces WHERE user_id = ?').bind(user.userId).first<{data:string;plan:string}>();return Response.json({user:{name:user.fullName||user.email.split('@')[0],email:user.email},state:row?JSON.parse(row.data):empty,plan:row?.plan||'free'},{headers:{'Cache-Control':'private, no-store'}})}catch(e){console.error('Workspace read failed',e);return Response.json({error:'Your workspace could not load. Please retry.'},{status:503})}}
export async function PUT(req:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in to save your workspace.'},{status:401});const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)return Response.json({error:'Invalid request origin.'},{status:403});try{const raw=await req.text();if(raw.length>800000)return Response.json({error:'Workspace is too large.'},{status:413});const parsed=schema.safeParse(JSON.parse(raw));if(!parsed.success)return Response.json({error:'Check your fields and try again.'},{status:400});await database().prepare('INSERT INTO workspaces (user_id, data, plan, updated_at) VALUES (?, ?, ?, ?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data, updated_at=excluded.updated_at').bind(user.userId,JSON.stringify(parsed.data),'free',new Date().toISOString()).run();return Response.json({ok:true})}catch(e){console.error('Workspace save failed',e);return Response.json({error:'Could not save your changes. Keep this page open and retry.'},{status:503})}}
