import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'umich-audit-'));
try{
 const outfile=join(dir,'test.mjs');
 await build({stdin:{contents:`export * from './app/campus-programs';export * from './app/campus-plan';export * from './app/campus-audit';`,resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',outfile});
 const {campusAudit,campusProgress,campusProgram,emptyCampusPlan}=await import(pathToFileURL(outfile));
 const plan=(track='CS-LSA',extra={})=>({...emptyCampusPlan,track,...extra});
 const audit=(codes,track='CS-LSA',extra={})=>campusAudit('umich',codes.map(c=>'umich:'+c),plan(track,extra));
 const row=(a,id)=>a.rows.find(r=>r.id===id);
 assert.equal(campusAudit('umich',[],emptyCampusPlan).total,0,'program selection required');
 assert.equal(campusProgram('umich',plan()).credits,120);
 assert.equal(campusProgram('umich',plan('CS-Eng')).credits,128);
 assert.equal(campusProgress('umich',[],plan('CS-Eng',{otherCredits:64})).percent,50);
 assert.equal(row(audit(['MATH 115','MATH 185']),'math').earned,1,'same math area only once');
 assert.equal(row(audit(['MATH 115','MATH 214']),'math').complete,true);
 assert.equal(row(audit(['EECS 388','EECS 442','EECS 445','EECS 453']),'ulcs-total').complete,true);
 assert.equal(row(audit(['EECS 388','EECS 453','EECS 460','EECS 461']),'ulcs-total').earned,7,'expanded cap of 3');
 assert.equal(row(audit(['EECS 388','EECS 442','EECS 445','EECS 481']),'ulcs-total').complete,true);
 assert.equal(row(audit(['EECS 498','CSE 598']),'ulcs-total').earned,0,'unapproved topics excluded');
 assert.equal(row(audit(['EECS 470']),'capstone').complete,false,'current architecture capstone is 472');
 assert.equal(row(audit(['EECS 472']),'capstone').complete,true);
 assert.equal(row(audit(['EECS 388'],'CS-LSA',{creditOverrides:{'EECS 388':0}}),'ulcs-total').earned,0);
 assert.equal(row(audit(['CHEM 125','CHEM 126'],'CS-Eng'),'chemistry').complete,false);
 assert.equal(row(audit(['CHEM 125','CHEM 126','CHEM 130'],'CS-Eng'),'chemistry').complete,true);
 assert.equal(row(audit(['CHEM 210','CHEM 211'],'CS-Eng'),'chemistry').complete,true);
 assert.equal(row(audit(['ROB 204'],'CS-Eng'),'communication').complete,true);
 assert.equal(row(audit(['EECS 473'],'CS-Eng'),'technical-total').earned,0,'capstone excluded from flex');
 assert.equal(row(audit(['EECS 473','EECS 497'],'CS-Eng'),'technical-total').earned,4,'reserve non-flex capstone');
 assert.equal(row(audit(['EECS 370','EECS 376','EECS 301'],'CS-Eng'),'technical-total').earned,0,'required courses excluded');
 assert.equal(row(audit(['EECS 399','EECS 499'],'CS-Eng',{creditOverrides:{'EECS 399':4,'EECS 499':4}}),'technical-total').earned,4,'research capped');
 assert.equal(row(audit(['MATH 425','STATS 425'],'CS-Eng'),'technical-total').earned,0,'cross-list does not fill stats and elective');
 assert.equal(audit(['EECS 203','EECS 280','EECS 281','EECS 370','EECS 376','STATS 250','MATH 115','MATH 116','EECS 388','EECS 442','EECS 445','EECS 481','EECS 497']).percent,100);
 assert.equal(campusAudit('umich',['umd:CMSC 131'],plan()).percent,0,'school isolation');
 console.log('Michigan audits passed: program totals, math areas, ULCS limits, capstones, chemistry alternatives, waivers, research caps and double-count prevention.');
}finally{await rm(dir,{recursive:true,force:true})}
