'use client';
import {useEffect,useRef,useState} from 'react';
import CodeEditor from '../code-editor';
import {type SavedState,OutLink} from '../workspace';
import {useNotebookKernel,type CellRun} from '../project-lab/notebook-kernel';
import {useLocalModel} from './local-model';
import {repoId,fileNames,editableFiles,freshRepo,repoProgram,selectedContext,contextLimit,copilotPrompt,type RepoSession,type RepoFile,type RepoMessage} from './repository';
type Props={state:SavedState;save:(state:SavedState)=>Promise<boolean>;saving:boolean};
export default function InterviewWorkspace({state,save,saving}:Props){
 const [session,setSession]=useState<RepoSession>(()=>state.repoSessions?.[repoId]||freshRepo());
 const [saved,setSaved]=useState(()=>JSON.stringify(state.repoSessions?.[repoId]||freshRepo()));
 const [input,setInput]=useState(''),[tab,setTab]=useState<RepoFile>('README.md'),[result,setResult]=useState<CellRun|null>(null),[error,setError]=useState(''),[sending,setSending]=useState(false),[confirmReset,setConfirmReset]=useState(false);
 const current=useRef(session);current.current=session;
 const turn=useRef(0),end=useRef<HTMLDivElement>(null),model=useLocalModel(),kernel=useNotebookKernel([]);
 const dirty=JSON.stringify(session)!==saved,stale=result&&result.source!==JSON.stringify(session.files);
 const testText=result?(stale?'Results are stale; code changed. ': '')+(result.error||result.outputs.filter(o=>o.kind==='table').map(o=>o.kind==='table'?o.rows.map(r=>r.join(' | ')).join('\n'):'').join('\n')):'Not run';
 const busy=sending||kernel.busy,context=selectedContext(session),overBudget=context.length>contextLimit;
 function selectFile(path:RepoFile){setSession(p=>({...p,selected:p.selected.includes(path)?p.selected.filter(f=>f!==path):[...p.selected,path]}))}
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'})},[session.messages]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(JSON.stringify(current.current)!==saved){e.preventDefault();e.returnValue=''}};const navigate=(e:MouseEvent)=>{const a=(e.target as HTMLElement).closest('a');if(a&&a.target!=='_blank'&&!a.hasAttribute('download')&&JSON.stringify(current.current)!==saved&&!confirm('Unsaved interview changes. Leave without saving?'))e.preventDefault()};addEventListener('beforeunload',leave);document.addEventListener('click',navigate,true);return()=>{removeEventListener('beforeunload',leave);document.removeEventListener('click',navigate,true)}},[saved]);
 useEffect(()=>()=>{turn.current++},[]);
 async function persist(){if(await save({...state,repoSessions:{...state.repoSessions,[repoId]:session}}))setSaved(JSON.stringify(session))}
 async function run(){setError('');const files=session.files;try{const r=await kernel.execute(repoProgram(files),'');setResult({...r,source:JSON.stringify(files)})}catch(e){setError((e as Error).message)}}
 async function send(text=input){if(!text.trim()||busy||!model.ready||model.busy||overBudget)return;const id=++turn.current;setSending(true);setInput('');const prior=current.current.messages;const messages:RepoMessage[]=[...prior,{role:'user' as const,content:text.slice(0,1500),attachments:[...session.selected],includedTests:session.includeTests}].slice(-38);setSession(p=>({...p,messages:[...messages,{role:'assistant',content:''}]}));
  const history=messages.slice(-3);while(history[0]?.role==='assistant')history.shift();
  try{await model.reply([{role:'system',content:copilotPrompt},...history.map((m,i)=>({role:m.role,content:i===history.length-1?'ATTACHED FILES (complete current contents):\n'+(context||'None. Ask me to attach files when needed.')+(session.includeTests?'\nTEST OUTPUT:\n'+testText.slice(0,1800):'\nTest output not attached.')+'\nMY REQUEST: '+m.content.slice(0,1500):m.content.slice(0,700)}))],content=>{if(turn.current===id)setSession(p=>({...p,messages:[...messages,{role:'assistant',content}]}))});}catch(e){setError((e as Error).message)}
  if(turn.current===id){setSession(p=>({...p,messages:p.messages.map((m,i)=>i===p.messages.length-1&&!m.content?{...m,content:'No reply was generated. Check the model status and send your message again.'}:m)}));setSending(false)}
 }
 function stop(){turn.current++;model.stop();setSending(false);setSession(p=>({...p,messages:p.messages.map((m,i)=>sending&&i===p.messages.length-1&&m.role==='assistant'?{...m,content:(m.content||'Generation stopped.').slice(0,2980)+'\n[Interrupted]'}:m)}))}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({project:'SupportDesk debugging',...session},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='supportdesk-session.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="interview-workspace">
 <div className="interview-intro"><div><h2>Debug with a copilot</h2><p>SupportDesk · 12 files · Python · 3 bug reports</p></div><div className="interview-actions"><button className="secondary" disabled={saving||busy} onClick={persist}>{saving?'Saving…':'Save workspace'}</button><button className="secondary" onClick={download}>Export</button><button className="text-link" disabled={busy} onClick={()=>setConfirmReset(true)}>Start over</button></div></div>
 <p className="muted">{dirty?'Unsaved changes':'Session saved'} · Save keeps your code and chat in your workspace. AI runs on your device; signed-in saves sync to your account.</p>
 {confirmReset&&<div className="notice"><p>Replace this repository’s edits, investigation notes and conversation with a fresh session?</p><button className="secondary" onClick={()=>{setSession(freshRepo());setResult(null);setInput('');setConfirmReset(false)}}>Reset session</button><button className="text-link" onClick={()=>setConfirmReset(false)}>Cancel</button></div>}
 <details className="repo-brief" open><summary>The assignment</summary><p>Customers report missed SLA deadlines, ticket updates leaking between queues, and duplicate notifications. Trace the code across modules, ask the copilot focused questions, and make the repairs yourself. Run the tests to check AI advice.</p><p>Start with README.md and the failing tests. Your investigation matters: choose relevant context, explain your hypothesis, and verify each change. This is original practice, not an official assessment or AI-generated hiring score.</p></details>
 <div className="interview-grid"><div className="interview-repo"><div className="repo-browser"><nav className="repo-tree" aria-label="Repository files"><strong>Files</strong><small>Checkboxes attach files to chat.</small>{fileNames.map(path=><div key={path}><input type="checkbox" aria-label={'Attach '+path} checked={session.selected.includes(path)} disabled={sending} onChange={()=>selectFile(path)}/><button className={tab===path?'selected':''} aria-current={tab===path?'page':undefined} onClick={()=>setTab(path)}>{path}{session.files[path]!==freshRepo().files[path]?' *':''}</button></div>)}</nav><div className="repo-file"><div className="repo-file-heading"><strong>{tab}</strong><span>{editableFiles.includes(tab)?'Editable':'Read only'}</span></div>{editableFiles.includes(tab)?<CodeEditor key={tab} label={'Code for '+tab} language="python" value={session.files[tab]} disabled={kernel.busy} onChange={code=>{if(code.length<=10000&&Object.entries(session.files).reduce((sum,[name,value])=>sum+(name===tab?code.length:value.length),0)<=60000)setSession(p=>({...p,files:{...p.files,[tab]:code}}))}}/>:<pre className="interview-test-source">{session.files[tab]}</pre>}</div></div>
 <div className="interview-actions"><button className="primary" disabled={kernel.busy} onClick={run}>{kernel.busy?'Running…':'Run 18 tests'}</button>{kernel.busy&&<button className="secondary" onClick={()=>kernel.stop()}>Stop tests</button>}<span role="status">{kernel.status}</span></div>
 {error&&<p role="alert">{error}</p>}{result&&<div className="interview-results" aria-label="Test results">{stale&&<p>Code changed. Run tests again.</p>}{result.error?<pre>{result.error}</pre>:result.outputs.map((o,i)=>o.kind==='table'?<table key={i}><thead><tr>{o.columns.slice(1).map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{o.rows.map((row,j)=><tr key={j}>{row.slice(1).map((v,k)=><td key={k}>{v}</td>)}</tr>)}</tbody></table>:o.kind==='text'?<pre key={i}>{o.text}</pre>:null)}</div>}
 <details className="repo-notes"><summary>Investigation notes</summary><label htmlFor="investigation-notes">What did you suspect? Which AI suggestions did you accept or reject, and what tests verified the repair?</label><textarea id="investigation-notes" rows={5} maxLength={3000} value={session.notes} onChange={e=>setSession(p=>({...p,notes:e.target.value}))}/></details>
 </div><div className="interview-chat"><div className="interview-chat-heading"><h2>Copilot</h2><span>Suggests changes · you apply them</span></div>
 <div className="repo-context"><strong>Attached context · {session.selected.length} files</strong><p>{context.length.toLocaleString()} / {contextLimit.toLocaleString()} characters</p><div className="repo-context-chips">{session.selected.map(path=><button disabled={sending} key={path} aria-label={'Remove '+path+' from context'} onClick={()=>selectFile(path)}>{path} ×</button>)}</div><label><input type="checkbox" checked={session.includeTests} disabled={sending} onChange={e=>setSession(p=>({...p,includeTests:e.target.checked}))}/>Include latest test output{stale?' (stale)':''}</label><details><summary>Preview attached files</summary><pre>{context||'No files selected.'}</pre></details>{overBudget&&<p role="alert">Too much context for the local model. Deselect files before sending; files will not be silently truncated.</p>}<small>Only selected file contents are attached to the next message. Previous chat may still mention files discussed earlier.</small></div>
 {!model.ready&&!model.busy&&<div className="interview-model"><p>Free local chat · no API key or paid credits.</p><p>Qwen Coder 3B downloads roughly 2 GB once and needs about 3 GB of GPU memory. Use a WebGPU-capable browser. Model files come from Hugging Face and WebLLM; chat generation stays here.</p><button className="primary" onClick={model.load}>Load local AI</button><OutLink href="https://webllm.mlc.ai/docs/">Runtime details</OutLink></div>}
 <p className="interview-model-status" role="status">{model.status}</p>{model.error&&<p className="notice" role="alert">{model.error}</p>}{(model.busy||model.ready)&&<button className="text-link" onClick={stop}>{model.busy?'Stop AI':'Unload model'}</button>}
 <div className="interview-messages" role="log" aria-label="Interview conversation" aria-live="polite">{!session.messages.length&&<p>Attach files using the repository checkboxes, load the model, and ask a focused question about a failing test or suspected bug.</p>}{session.messages.map((m,i)=><article key={i}><strong>{m.role==='user'?'You':'AI'}</strong>{m.role==='user'&&<small>Attached: {m.attachments?.join(', ')||'No files'}{m.includedTests?' · Test output':''}</small>}<p>{m.content||'Thinking…'}</p></article>)}<div ref={end}/></div>
 <div className="interview-prompts"><button className="text-link" disabled={!model.ready||model.busy||busy||overBudget} onClick={()=>send('Help me trace the failing tests through the attached files. Suggest one likely root cause; ask for another file if context is missing.')}>Investigate a failure</button><button className="text-link" disabled={!model.ready||model.busy||busy||overBudget} onClick={()=>send('Review the attached changes against the available test results. Explain remaining risks and suggest one verification step.')}>Review my changes</button></div>
 <form onSubmit={e=>{e.preventDefault();send()}}><label htmlFor="interview-message">Your message</label><textarea id="interview-message" value={input} maxLength={1500} rows={3} onChange={e=>setInput(e.target.value)} placeholder="Why is this test failing? What else should I inspect?"/><button className="primary" disabled={!model.ready||model.busy||busy||overBudget||!input.trim()}>Send</button></form><small>AI feedback can be wrong. Use test results to verify changes. The latest 40 messages are saved; recent messages fit into the model’s limited context.</small>
 </div></div></section>;
}
