'use client';
import {useEffect,useRef,useState} from 'react';
import CodeEditor from '../code-editor';
import {type SavedState,OutLink} from '../workspace';
import {useNotebookKernel,type CellRun} from '../project-lab/notebook-kernel';
import {useLocalModel} from './local-model';
import {brief,starter,tests,interviewId,freshInterview,testProgram,chatContext,type InterviewProgress,type InterviewMessage} from './exercise';
type Props={state:SavedState;save:(state:SavedState)=>Promise<boolean>;saving:boolean};
export default function InterviewWorkspace({state,save,saving}:Props){
 const [session,setSession]=useState<InterviewProgress>(()=>state.interviews?.[interviewId]||freshInterview());
 const [saved,setSaved]=useState(()=>JSON.stringify(state.interviews?.[interviewId]||freshInterview()));
 const [input,setInput]=useState(''),[tab,setTab]=useState('queue.py'),[result,setResult]=useState<CellRun|null>(null),[error,setError]=useState(''),[sending,setSending]=useState(false),[confirmReset,setConfirmReset]=useState(false);
 const current=useRef(session);current.current=session;
 const turn=useRef(0),end=useRef<HTMLDivElement>(null),model=useLocalModel(),kernel=useNotebookKernel([]);
 const dirty=JSON.stringify(session)!==saved,stale=result&&result.source!==session.code;
 const testText=result?(stale?'Results are stale; code changed. ': '')+(result.error||result.outputs.filter(o=>o.kind==='table').map(o=>o.kind==='table'?o.rows.map(r=>r.join(' | ')).join('\n'):'').join('\n')):'Not run';
 const busy=sending||kernel.busy;
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'})},[session.messages]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(JSON.stringify(current.current)!==saved){e.preventDefault();e.returnValue=''}};const navigate=(e:MouseEvent)=>{const a=(e.target as HTMLElement).closest('a');if(a&&a.target!=='_blank'&&!a.hasAttribute('download')&&JSON.stringify(current.current)!==saved&&!confirm('Unsaved interview changes. Leave without saving?'))e.preventDefault()};addEventListener('beforeunload',leave);document.addEventListener('click',navigate,true);return()=>{removeEventListener('beforeunload',leave);document.removeEventListener('click',navigate,true)}},[saved]);
 useEffect(()=>()=>{turn.current++},[]);
 async function persist(){if(await save({...state,interviews:{...state.interviews,[interviewId]:session}}))setSaved(JSON.stringify(session))}
 async function run(){setError('');const code=session.code;try{const r=await kernel.execute(testProgram(code),'');setResult({...r,source:code})}catch(e){setError((e as Error).message)}}
 async function send(text=input){if(!text.trim()||busy||!model.ready||model.busy)return;const id=++turn.current;setSending(true);setInput('');const prior=current.current.messages;const messages:InterviewMessage[]=[...prior,{role:'user' as const,content:text.slice(0,1500)}].slice(-38);setSession(p=>({...p,messages:[...messages,{role:'assistant',content:''}]}));
  const history=messages.slice(-5);while(history[0]?.role==='assistant')history.shift();
  await model.reply([{role:'system',content:chatContext(session.mode,'','')},...history.map((m,i)=>({...m,content:i===history.length-1?'CURRENT queue.py:\n'+session.code.slice(0,4500)+'\nACTUAL TEST OUTPUT:\n'+testText.slice(0,1800)+'\nMY REQUEST: '+m.content.slice(0,1000):m.content.slice(0,1000)}))],content=>{if(turn.current===id)setSession(p=>({...p,messages:[...messages,{role:'assistant',content}]}))});
  if(turn.current===id){setSession(p=>({...p,messages:p.messages.map((m,i)=>i===p.messages.length-1&&!m.content?{...m,content:'No reply was generated. Check the model status and send your message again.'}:m)}));setSending(false)}
 }
 function stop(){turn.current++;model.stop();setSending(false);setSession(p=>({...p,messages:p.messages.map((m,i)=>sending&&i===p.messages.length-1&&m.role==='assistant'?{...m,content:(m.content||'Generation stopped.').slice(0,2980)+'\n[Interrupted]'}:m)}))}
 function download(){const text=['# Support queue interview',brief,'```python',session.code,'```',...session.messages.map(m=>`## ${m.role==='user'?'You':'AI'}\n${m.content}`)].join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download='support-queue-interview.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="interview-workspace">
 <div className="interview-intro"><div><h2>Support queue repair</h2><p>Original repository exercise · Python · about 25 minutes</p></div><div className="interview-actions"><button className="secondary" disabled={saving||busy} onClick={persist}>{saving?'Saving…':'Save session'}</button><button className="secondary" onClick={download}>Export</button><button className="text-link" disabled={busy} onClick={()=>setConfirmReset(true)}>Start over</button></div></div>
 <p className="muted">{dirty?'Unsaved changes':'Session saved'} · Save keeps your code and chat in your workspace. AI runs on your device; signed-in saves sync to your account.</p>
 {confirmReset&&<div className="notice"><p>Replace this exercise’s code and conversation with a fresh session?</p><button className="secondary" onClick={()=>{setSession(freshInterview());setResult(null);setInput('');setConfirmReset(false)}}>Reset session</button><button className="text-link" onClick={()=>setConfirmReset(false)}>Cancel</button></div>}
 <div className="interview-grid"><div className="interview-repo"><details open><summary>Task & requirements</summary><p>{brief}</p><p>Explain your approach, repair the code, run the tests, then ask for feedback. This is independent practice, not an official Amazon question or score.</p></details>
 <nav className="interview-files" aria-label="Exercise files">{['queue.py','test_queue.py'].map(file=><button key={file} aria-pressed={tab===file} className={tab===file?'primary':'secondary'} onClick={()=>setTab(file)}>{file}</button>)}</nav>
 {tab==='queue.py'?<CodeEditor label="Interview code" language="python" value={session.code} disabled={kernel.busy} onChange={code=>{if(code.length<=10000)setSession(p=>({...p,code}))}}/>:<pre className="interview-test-source">{tests}</pre>}
 <div className="interview-actions"><button className="primary" disabled={kernel.busy} onClick={run}>{kernel.busy?'Running…':'Run 11 tests'}</button>{kernel.busy&&<button className="secondary" onClick={()=>kernel.stop()}>Stop tests</button>}<span role="status">{kernel.status}</span></div>
 {error&&<p role="alert">{error}</p>}{result&&<div className="interview-results" aria-label="Test results">{stale&&<p>Code changed. Run tests again.</p>}{result.error?<pre>{result.error}</pre>:result.outputs.map((o,i)=>o.kind==='table'?<table key={i}><thead><tr>{o.columns.slice(1).map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{o.rows.map((row,j)=><tr key={j}>{row.slice(1).map((v,k)=><td key={k}>{v}</td>)}</tr>)}</tbody></table>:o.kind==='text'?<pre key={i}>{o.text}</pre>:null)}</div>}
 </div><div className="interview-chat"><div className="interview-chat-heading"><h2>AI interviewer</h2><label>Mode<select aria-label="AI mode" disabled={sending} value={session.mode} onChange={e=>setSession(p=>({...p,mode:e.target.value as InterviewProgress['mode']}))}><option value="interviewer">Interview me</option><option value="assistant">Help me code</option></select></label></div>
 {!model.ready&&!model.busy&&<div className="interview-model"><p>Free local chat · no API key or paid credits.</p><p>Qwen Coder 3B downloads roughly 2 GB once and needs about 3 GB of GPU memory. Use a WebGPU-capable browser. Model files come from Hugging Face and WebLLM; chat generation stays here.</p><button className="primary" onClick={model.load}>Load local AI</button><OutLink href="https://webllm.mlc.ai/docs/">Runtime details</OutLink></div>}
 <p className="interview-model-status" role="status">{model.status}</p>{model.error&&<p className="notice" role="alert">{model.error}</p>}{(model.busy||model.ready)&&<button className="text-link" onClick={stop}>{model.busy?'Stop AI':'Unload model'}</button>}
 <div className="interview-messages" role="log" aria-label="Interview conversation" aria-live="polite">{!session.messages.length&&<p>Load the model, then introduce your approach or ask for your first interview question. The AI receives your current code and latest test results.</p>}{session.messages.map((m,i)=><article key={i}><strong>{m.role==='user'?'You':'AI'}</strong><p>{m.content||'Thinking…'}</p></article>)}<div ref={end}/></div>
 <div className="interview-prompts"><button className="text-link" disabled={!model.ready||model.busy||busy} onClick={()=>send('Start the interview. Ask me one question about my approach.')}>Start interview</button><button className="text-link" disabled={!model.ready||model.busy||busy} onClick={()=>send('Review my current code and test results. Give specific feedback and one follow-up question.')}>Review my code</button></div>
 <form onSubmit={e=>{e.preventDefault();send()}}><label htmlFor="interview-message">Your message</label><textarea id="interview-message" value={input} maxLength={1500} rows={3} onChange={e=>setInput(e.target.value)} placeholder="Explain your approach, ask for a hint…"/><button className="primary" disabled={!model.ready||model.busy||busy||!input.trim()}>Send</button></form><small>AI feedback can be wrong. Use test results to verify changes. The latest 40 messages are saved; recent messages fit into the model’s limited context.</small>
 </div></div></section>;
}
