'use client';
import {useEffect,useRef,useState} from 'react';
import {Copy,Check,ArrowLeft,ArrowRight} from 'lucide-react';
import {OutLink} from './workspace';
const sections=[['basics','What AI coding tools do'],['setup','Install & sign in'],['project','Create a practice project'],['investigate','Understand before editing'],['fix','Fix one bug'],['review','Test & review the change'],['context','Give your next session context']] as const;
export function Snippet({label,children}:{label:string;children:string}){const [copied,setCopied]=useState(false),[failed,setFailed]=useState(false);return <div className="course-snippet"><div><span>{label}</span><button className="text-link" aria-label={'Copy '+label} onClick={async()=>{try{await navigator.clipboard.writeText(children);setCopied(true);setFailed(false);setTimeout(()=>setCopied(false),1800)}catch{setFailed(true)}}}>{copied?<Check size={14}/>:<Copy size={14}/>}<span>{copied?'Copied':'Copy'}</span></button></div><pre><code>{children}</code></pre>{failed&&<span role="status">Select the text to copy it manually.</span>}</div>}
export function Checkpoint({question,children}:{question:string;children:React.ReactNode}){return <div className="course-check"><h3>Check your understanding</h3><p>{question}</p><details><summary>Show answer</summary><p>{children}</p></details></div>}
const starter=`def clean_tags(tags):
    return [tag.lower() for tag in tags]
`;
const tests=`import unittest
from tags import clean_tags

class CleanTagsTests(unittest.TestCase):
    def test_lowercases_tags(self):
        self.assertEqual(clean_tags(["Python", "AI"]), ["python", "ai"])

    def test_empty_input(self):
        self.assertEqual(clean_tags([]), [])

if __name__ == "__main__":
    unittest.main()
`;
export default function AiCourse(){const [active,setActive]=useState(0),[system,setSystem]=useState('mac');const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{const sync=()=>{const i=sections.findIndex(s=>s[0]===location.hash.slice(1));setActive(i<0?0:i)};sync();addEventListener('hashchange',sync);return()=>removeEventListener('hashchange',sync)},[]);
 function select(i:number){setActive(i);requestAnimationFrame(()=>heading.current?.focus())}
 return <div className="course-layout"><nav className="course-toc" aria-label="Course sections"><h2>Claude Code fundamentals</h2><ol>{sections.map(([id,title],i)=><li key={id}><a href={'#'+id} onClick={()=>select(i)} aria-current={active===i?'step':undefined}><span>{i+1}</span>{title}</a></li>)}</ol></nav><article key={active} className="course-lesson" id={sections[active][0]}><p className="course-position">Section {active+1} of {sections.length}</p><h2 ref={heading} tabIndex={-1}>{sections[active][1]}</h2>
 {active===0&&<><p>This course takes you through one small Python bug fix with Claude Code. You’ll inspect the code, define the expected behavior, test a change, and decide whether to keep it.</p><h3>1. Know what can act on your files</h3><p>A coding assistant can explain code in conversation. An agent such as Claude Code also has tools to read files, edit them, and run terminal commands. Check the action it actually performed, not just the explanation it gave.</p><h3>2. Separate a suggestion from evidence</h3><p>“This should work” is a prediction. A test command and its output are evidence about specific inputs. Neither proves that every possible input works. Your job is to define the behavior and inspect what changed.</p><h3>3. Prepare for the exercise</h3><ul><li>You need basic Python, Python 3, Git, and a terminal.</li><li>Use the small project in section 3; no existing repository is required.</li><li>Claude Code requires separate Anthropic access. Signing into this student guide with ChatGPT does not provide it.</li><li>For coursework, check your class’s AI rules before using an assistant on an assignment.</li></ul><Checkpoint question="Claude says it fixed a bug. What would you check before accepting the change?">Inspect the diff, run a test that reproduces the original bug, and run the existing tests. Confirm the result matches the behavior you wanted.</Checkpoint><OutLink href="https://code.claude.com/docs/en/how-claude-code-works">How Claude Code works</OutLink></>}
 {active===1&&<><h3>1. Install the terminal tool</h3><p>Choose your system. These are Anthropic’s installation commands; run them in your computer’s terminal.</p><div className="course-os" role="group" aria-label="Operating system">{[['mac','macOS / Linux / WSL'],['windows','Windows PowerShell']].map(([id,label])=><button key={id} className="secondary" aria-pressed={system===id} onClick={()=>setSystem(id)}>{label}</button>)}</div><Snippet label="Terminal — install">{system==='mac'?'curl -fsSL https://claude.ai/install.sh | bash':'irm https://claude.ai/install.ps1 | iex'}</Snippet><h3>2. Verify installation</h3><p>Open a new terminal, then run:</p><Snippet label="Terminal — verify">claude --version</Snippet><p>You should see a version number. If the command is not found, follow the PATH instructions in the official setup guide below.</p><h3>3. Sign in</h3><Snippet label="Terminal — start">claude</Snippet><p>Follow the browser login prompts with your Claude subscription or Console account. Access and billing belong to Anthropic. Inside the session, use <code>/help</code> for commands and <code>/exit</code> to return to your terminal.</p><OutLink href="https://code.claude.com/docs/en/quickstart">Official installation & account requirements</OutLink><Checkpoint question="Where do you type /help: your ordinary terminal prompt, or inside Claude Code?">Inside a running Claude Code session. The terminal command “claude” starts that session.</Checkpoint></>}
 {active===2&&<><p>We’ll normalize a list of topic tags. The starter lowercases text but deliberately leaves spaces and empty tags unchanged.</p><h3>1. Create an empty folder</h3><Snippet label="Terminal — new project">{'mkdir ai-tags-lab\ncd ai-tags-lab\ngit init'}</Snippet><h3>2. Create two files in your editor</h3><p>Save both files in <code>ai-tags-lab</code>. These snippets are complete; no third-party Python packages are needed.</p><Snippet label="tags.py">{starter}</Snippet><Snippet label="test_tags.py">{tests}</Snippet><h3>3. Run the baseline tests</h3><Snippet label="Terminal — tests">python3 -m unittest -v</Snippet><p>On Windows, use <code>py -3 -m unittest -v</code>. Expect two passing tests. If Python cannot import <code>tags</code>, check that both files are in the current folder.</p><h3>4. Save a starting point</h3><Snippet label="Terminal — checkpoint">{'git add tags.py test_tags.py\ngit commit -m "Add tag normalization starter"'}</Snippet><p>If Git asks for your identity, configure your own name and email using Git’s instructions, then retry the commit. Start Claude from this folder:</p><Snippet label="Terminal — open project">claude</Snippet><Checkpoint question="Why can both tests pass even though the function has a bug?">They only cover lowercase conversion and an empty list. There is no test yet for surrounding whitespace or blank strings.</Checkpoint></>}
 {active===3&&<><h3>1. Ask for an explanation with file references</h3><Snippet label="Prompt — inspect">{'Read tags.py and test_tags.py. Explain what clean_tags does today and which behaviors the tests cover. Reference the relevant functions. Do not edit files or run commands yet.'}</Snippet><p>Open the files yourself. Confirm that the explanation matches the list comprehension and the two assertions.</p><h3>2. State the missing behavior</h3><p>For this exercise, inputs are lists of strings. We want lowercase tags with surrounding whitespace removed, blank tags omitted, and the original order preserved. Duplicates should stay.</p><Snippet label="Example — desired result">{'Input:  [" Python ", "", "  ", "AI", "Python"]\nOutput: ["python", "ai", "python"]'}</Snippet><h3>3. Ask for a plan</h3><Snippet label="Prompt — plan">{'Plan a minimal change to clean_tags: lowercase each string, strip surrounding whitespace, omit empty results, preserve order and duplicates. Suggest regression tests. Do not implement it yet or add dependencies.'}</Snippet><p>Read the plan. Reject unrelated changes such as sorting tags, removing duplicates, or adding a web interface. A request to “improve the code” leaves those decisions open.</p><Checkpoint question="Would converting the tags to a set satisfy this exercise?">No. A set removes duplicates, and our specified behavior preserves both duplicates and their order.</Checkpoint><OutLink href="https://code.claude.com/docs/en/common-workflows">Claude Code workflow reference</OutLink></>}
 {active===4&&<><h3>1. Capture the bug in a test</h3><p>Ask for a failing test before changing the implementation:</p><Snippet label="Prompt — regression test">{'Add one test to test_tags.py using input [" Python ", "", "  ", "AI", "Python"] and expected output ["python", "ai", "python"]. Run the suite and show the failure. Do not modify tags.py yet.'}</Snippet><p>Check that the failure compares the old output with the expected list. A missing import or syntax error is not evidence of the intended bug.</p><h3>2. Implement the agreed behavior</h3><Snippet label="Prompt — fix">{'Now update only clean_tags to satisfy the behavior we agreed on. Keep its name and argument unchanged. Use the Python standard library only. Rerun all tests and show the results.'}</Snippet><p>Pay attention to the permission mode shown in Claude Code. Some modes permit edits or commands automatically. Review requested actions when prompted; a sentence in your prompt is not a security boundary.</p><h3>3. Read the implementation</h3><p>Find where the solution removes whitespace, lowercases the text, and excludes empty results. If you cannot explain a line, ask Claude to walk through it with the example input.</p><Checkpoint question="Should you accept a fix that changes the expected result to match the old output?">No. The expected result comes from the agreed behavior. Changing the assertion to accept the bug defeats the regression test.</Checkpoint><OutLink href="https://code.claude.com/docs/en/how-claude-code-works">Tool actions & permission modes</OutLink></>}
 {active===5&&<><h3>1. Run the tests yourself</h3><p>Use <code>/exit</code> to leave Claude Code, then run the suite in the project folder:</p><Snippet label="Terminal — verify">{'python3 -m unittest -v\ngit diff --check\ngit diff'}</Snippet><p>Use <code>py -3</code> instead of <code>python3</code> on Windows. The suite should now include the two original tests and the new regression test. The diff should show only the intended function and test edits.</p><h3>2. Try a case the assistant did not choose</h3><p>Add this method inside <code>CleanTagsTests</code>, then run the suite again:</p><Snippet label="test_tags.py — additional test">{'    def test_only_blank_tags(self):\n        self.assertEqual(clean_tags(["", "   ", "\\t"]), [])'}</Snippet><p>This checks whether the function returns an empty list when every input becomes blank. Think of one more input before looking at the reference implementation.</p><details className="compact-details"><summary>Compare with a reference solution</summary><Snippet label="tags.py — reference">{'def clean_tags(tags):\n    normalized = [tag.strip().lower() for tag in tags]\n    return [tag for tag in normalized if tag]\n'}</Snippet><p>Other implementations can also be correct. Judge them against the behavior and tests, not whether they match these lines.</p></details><h3>3. Keep the reviewed change</h3><Snippet label="Terminal — commit">{'git add tags.py test_tags.py\ngit commit -m "Trim tags and omit blank values"'}</Snippet><Checkpoint question="Does four passing tests prove the function works for every kind of input?">No. They provide evidence for those cases. This exercise assumes strings; support for numbers or null values would require a separate decision and tests.</Checkpoint><OutLink href="https://code.claude.com/docs/en/best-practices">Verification practices</OutLink></>}
 {active===6&&<><h3>1. Write down the project’s rules</h3><p>A <code>CLAUDE.md</code> file gives Claude Code project instructions across sessions. Keep it short and specific. Save this at the root of your practice project:</p><Snippet label="CLAUDE.md">{'# Tag normalization lab\n\n- Python standard library only; no dependencies.\n- Implementation: tags.py. Tests: test_tags.py.\n- Run tests: python3 -m unittest -v (Windows: py -3 -m unittest -v).\n- Inputs are lists of strings.\n- Output: lowercase, trimmed, nonempty tags.\n- Preserve order and duplicates.\n- Add a regression test before fixing a reported bug.\n- Do not commit unless I ask.'}</Snippet><p>These are instructions to a model, not enforced permissions. Update them when the project changes.</p><h3>2. Start a fresh session with a bounded task</h3><Snippet label="Prompt — next exercise">{'Read CLAUDE.md and the current code. Propose an optional unique=False argument for clean_tags. When True, remove duplicate normalized tags while preserving the first occurrence. Keep the default behavior unchanged. Plan the tests before editing.'}</Snippet><h3>3. Apply the same process independently</h3><ol><li>Write down the behavior of both argument values.</li><li>Inspect the plan and require a failing test for the new behavior.</li><li>Review the implementation and run the whole suite.</li><li>Explain the algorithm and its time complexity without looking at Claude’s explanation.</li></ol><Checkpoint question="What should happen to existing callers when unique is omitted?">Their behavior should stay the same: lowercase and trim tags, drop blanks, and preserve duplicates and order.</Checkpoint><p>You’ve finished the walkthrough. Use this sequence in your own projects: define the behavior, inspect the relevant code, test a small change, then review the result.</p><OutLink href="https://code.claude.com/docs/en/memory">Project instructions reference</OutLink></>}
 <footer className="course-navigation">{active>0?<a className="secondary" href={'#'+sections[active-1][0]} onClick={()=>select(active-1)}><ArrowLeft size={15}/>Previous</a>:<span/>}{active<sections.length-1?<a className="primary" href={'#'+sections[active+1][0]} onClick={()=>select(active+1)}>Next section<ArrowRight size={15}/></a>:<a className="secondary" href="#basics" onClick={()=>select(0)}>Back to beginning</a>}</footer><p className="source-note">Original practice exercise · Claude Code commands checked September 29, 2026.</p></article></div>
}
