import catalog from './campus-catalog.json';
import {campusCourseKey,type CampusPlan} from './campus-plan';
export type CampusId=keyof typeof catalog;
export type CampusCourse={code:string;title:string;credits:number|null;category:string;note:string;source:string};
type Program={degree:string;credits:number;source:string;scope:string;core:string[][];checks:[string,string][];extra:[string,string,number][]};
export const programs:Record<CampusId,Program>={
 umd:{degree:'B.S. Computer Science · General track',credits:120,source:'https://undergrad.cs.umd.edu/degree-requirements-cs-major/',scope:'General-track core and the department’s complete published distributive-area/elective list. Specializations have different distributions.',core:[['CMSC 131','CMSC 133'],['CMSC 132'],['CMSC 216'],['CMSC 250'],['CMSC 330'],['CMSC 351'],['MATH 140'],['MATH 141']],extra:[['CMSC 131','Object-Oriented Programming I',4],['CMSC 133','Object-Oriented Programming I Beyond Fundamentals',2],['CMSC 132','Object-Oriented Programming II',4],['CMSC 216','Introduction to Computer Systems',4],['CMSC 250','Discrete Structures',4],['CMSC 330','Organization of Programming Languages',3],['CMSC 351','Algorithms',3],['MATH 140','Calculus I',4],['MATH 141','Calculus II',4]],checks:[['distribution','Five 400-level CS courses across at least three distributive areas; no more than three from one area. CMSC 471 counts in Area 2 or 3, once.'],['electives','Two additional upper-level CS electives (six credits), excluding CMSC 330 and 351. Three one-credit STICs may fill one elective.'],['math','One eligible STAT 4xx and one additional MATH/STAT 3xx–4xx, each requiring MATH 141; no CMSC cross-listings.'],['concentration','Twelve credits at 300/400 level in one discipline outside CS, excluding CMSC cross-listings; meet the concentration GPA and experiential-credit limits.'],['gened','Finish General Education, residency, minimum grades, and university graduation requirements.']]},
 uiuc:{degree:'B.S. Computer Science · Grainger Engineering',credits:128,source:'https://catalog.illinois.edu/undergraduate/engineering/computer-science-bs/',scope:'Standard CS B.S.; CS + X and other combined degrees use different requirements. The catalog includes courses that do not qualify as technical electives.',core:[...['124','128','173','222','225','233','341','357','361','374','421'].map(n=>['CS '+n]),['CS 210','CS 211'],['MATH 220','MATH 221'],['MATH 231'],['MATH 241'],['MATH 257','MATH 415','MATH 416'],['PHYS 211'],['PHYS 212']],extra:[['MATH 220','Calculus (four credits apply to this degree)',4],['MATH 221','Calculus I',4],['MATH 231','Calculus II',3],['MATH 241','Calculus III',4],['MATH 257','Linear Algebra with Computational Applications',3],['MATH 415','Applied Linear Algebra',3],['MATH 416','Abstract Linear Algebra',3],['PHYS 211','University Physics: Mechanics',4],['PHYS 212','University Physics: Electricity & Magnetism',4]],checks:[['technical','At least six technical electives totaling 18 credits: CS 397 and eligible 400-level courses. Exclude CS 400–403, 421 and 491. CS 397/499 count for at most six credits combined.'],['team','Include a team-project course: CS 411, 415, 417, 425 (four credits), 427, 428, 429, 437, 465, 467, 493, 494 or 497.'],['focus','Complete three technical electives within one catalog focus area.'],['science','Complete an approved additional science elective of at least three credits.'],['gened','Complete engineering orientation, general education, language, residency, 40 upper-division credits, and GPA requirements.']]},
 gatech:{degree:'B.S. Computer Science · Two Threads',credits:124,source:'https://catalog.gatech.edu/programs/computer-science-bs/',scope:'Select your two-Thread combination under Requirements to see its curriculum. The foundation checklist is only the common starting point.',core:[['CS 1301'],['CS 1331'],['CS 1332'],['CS 2050','CS 2051']],extra:[],checks:[['threads','Complete the required courses and elective choices for your selected two Threads.'],['junior','Complete the approved junior-design or project pathway for your curriculum.'],['core','Complete mathematics, laboratory science, Core IMPACTS, ethics and other requirements in the selected curriculum.'],['wellness','Complete two wellness credits in addition to the 124 degree credits. Do not include wellness credits in the degree-credit total.'],['grades','Meet grade, GPA, residency and free-elective restrictions; required CS and Thread courses need C or better.']]},
 vt:{degree:'B.S. Computer Science',credits:123,source:'https://catalog.vt.edu/undergraduate/college-engineering/computer-science/computer-science-bs/',scope:'CS major foundation and the department’s published course offerings. Secure Computing and Data-Centric Computing are separate majors. Credits not stated in the offerings list must be entered from your record.',core:['1114','2104','2114','2505','2506','3114'].map(n=>['CS '+n]),extra:[['CS 1114','Introduction to Software Design',3],['CS 2104','Introduction to Problem Solving in Computer Science',3],['CS 2114','Software Design and Data Structures',3],['CS 2505','Introduction to Computer Organization I',3],['CS 2506','Introduction to Computer Organization II',3],['CS 3114','Data Structures and Algorithms',3]],checks:[['advanced','Complete the additional required CS courses, CS electives and technical electives in your catalog-year degree audit.'],['capstone','Complete the CS capstone. From spring 2026, the department uses CS 4094; older capstone numbers may appear on existing records.'],['math','Complete the required mathematics, statistics, engineering and laboratory science sequence.'],['pathways','Complete Pathways, communications, language and residency requirements. College language credits used only to meet the entrance-language requirement do not count toward the degree.'],['grades','Earn C or better in the six foundation courses; maintain at least 2.0 overall and CS GPAs.']]}
};
export function campusCourses(id:CampusId):CampusCourse[]{
 const p=programs[id],rows=new Map<string,CampusCourse>(catalog[id].map(c=>[c.code,{...c}]));
 for(const [code,title,credits] of p.extra)rows.set(code,{...rows.get(code),code,title,credits,category:'Foundation',note:'',source:p.source});
 for(const codes of p.core)for(const code of codes){const c=rows.get(code);if(c){c.category='Foundation';if(codes.length>1)c.note='Choose one: '+codes.join(' or ')+'. Count equivalent course credits only once.'}}
 return [...rows.values()].sort((a,b)=>a.code.localeCompare(b.code,undefined,{numeric:true}));
}
export function campusProgress(id:CampusId,completed:string[],plan:CampusPlan){
 const courses=campusCourses(id),done=new Set(completed),isDone=(code:string)=>done.has(campusCourseKey(id,code));
 const finished=courses.filter(c=>isDone(c.code));
 const credits=finished.reduce((sum,c)=>sum+(plan.creditOverrides[c.code]??c.credits??0),plan.otherCredits);
 const foundation=programs[id].core.filter(group=>group.some(isDone)).length;
 return {credits,percent:Math.min(100,Math.floor(100*credits/programs[id].credits)),foundation,foundationTotal:programs[id].core.length,completed:finished.length,unknownCredits:finished.filter(c=>c.credits===null&&plan.creditOverrides[c.code]===undefined).length,planned:courses.filter(c=>!isDone(c.code)&&plan.statuses[c.code]==='Planned').length,inProgress:courses.filter(c=>!isDone(c.code)&&plan.statuses[c.code]==='In progress').length};
}
