'use client';
import {useState} from 'react';
import {Search} from 'lucide-react';
import {OutLink,type SavedState} from './workspace';
import {emptyCampusPlan,campusCourseKey,type CampusPlan} from './campus-plan';
import {programs,campusCourses,campusProgress,type CampusId,type CampusCourse} from './campus-programs';
import {campusAudit} from './campus-audit';
import threadCatalog from './gatech-threads.json';
const statuses=['Not started','Planned','In progress','Completed'] as const;
type Status=typeof statuses[number];
export default function CampusPlanner({id,state,save,saving}:{id:CampusId;state:SavedState;save:(s:SavedState)=>Promise<boolean>;saving:boolean}){
 const p={...emptyCampusPlan,...state.collegePlans[id]},program=programs[id],courses=campusCourses(id),progress=campusProgress(id,state.courses,p),audit=campusAudit(id,state.courses,p);
 const [view,setView]=useState('Progress'),[query,setQuery]=useState(''),[filter,setFilter]=useState('All statuses'),[other,setOther]=useState(String(p.otherCredits));
 const update=(patch:Partial<CampusPlan>)=>save({...state,collegePlans:{...state.collegePlans,[id]:{...p,...patch}}});
 const status=(code:string):Status=>state.courses.includes(campusCourseKey(id,code))?'Completed':p.statuses[code]||'Not started';
 function changeStatus(code:string,value:Status){const next={...p.statuses};delete next[code];if(value==='Planned'||value==='In progress')next[code]=value;return save({...state,courses:[...state.courses.filter(c=>c!==campusCourseKey(id,code)),...(value==='Completed'?[campusCourseKey(id,code)]:[])],collegePlans:{...state.collegePlans,[id]:{...p,statuses:next}}})}
 const visible=courses.filter(c=>(view!=='Foundation'||c.category==='Foundation')&&(filter==='All statuses'||status(c.code)===filter)&&`${c.code} ${c.title} ${c.category}`.toLowerCase().includes(query.toLowerCase()));
 const pair=threadCatalog.find(t=>t.name===p.track);
 return <div className="degree-planner"><div className="planner-header"><span>{program.degree}</span></div>
 <div className="degree-metrics"><div><span>Degree credits</span><strong>{progress.percent}%</strong><progress aria-label="Degree credit progress" max={program.credits} value={Math.min(progress.credits,program.credits)}/><small>{progress.credits} / {program.credits} earned · {Math.max(0,program.credits-progress.credits)} remaining</small></div><div><span>Course requirements</span><strong>{audit.percent}%</strong><progress aria-label="Course requirement progress" max={100} value={audit.percent}/><small>{audit.complete} / {audit.total} requirements met</small></div><div><span>Your courses</span><strong>{progress.completed}<em> completed</em></strong><small>{progress.inProgress} in progress · {progress.planned} planned</small><button className="text-link" onClick={()=>setView('Other requirements')}>Add other earned credits</button></div></div>
 <p className="planner-caption">Course requirements update from completed classes. Degree credits also include the other earned credits you add.</p>
 <div className="planner-tabs" role="group" aria-label="Course planner sections">{['Progress','Course catalog','Other requirements'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>{setView(v);setQuery('');setFilter('All statuses')}}>{v}</button>)}</div>
 {id==='gatech'&&<div className="thread-picker"><label htmlFor="threads">Your two Threads</label><select id="threads" value={p.track} disabled={saving} onChange={e=>update({track:e.target.value})}><option value="">Choose a combination</option>{threadCatalog.map(t=><option key={t.name}>{t.name}</option>)}</select></div>}
 {view==='Progress'?<section className="course-audit" aria-label="Automatic course audit"><div className="audit-heading"><h2>What’s left</h2><p>Mark a course completed. Requirements update automatically.</p></div>
 {audit.rows.filter(r=>!r.id.startsWith('optional-')).sort((a,b)=>Number(a.complete)-Number(b.complete)).map(r=><details className={'audit-row '+(r.complete?'audit-complete':'')} key={r.id}>
 <summary><span><strong>{r.label}</strong><small>{r.complete?'Complete':r.earned>=r.required?'Credit requirement remaining':`${r.required-r.earned} ${r.required-r.earned===1?r.unit.replace(/s$/,''):r.unit} remaining`}</small></span><span className="audit-count">{r.earned} / {r.required}{r.complete?' ✓':''}</span></summary>
 <div className="audit-body">{r.detail&&<p>{r.detail}</p>}{r.completed.length>0&&<p className="audit-applied">{id==='uiuc'?'Completed eligible courses: ':'Applied: '}{r.completed.join(', ')}</p>}
 {r.alternatives?.some(a=>a.length>1)&&<p>Options: {r.alternatives.map(a=>a.join(' + ')).join(' OR ')}</p>}
 {r.id==='focus'&&<div className="focus-progress">{audit.rows.filter(f=>f.id.startsWith('optional-')).map(f=><p key={f.id}>{f.label}<span>{f.earned} / {f.required}</span></p>)}</div>}
 <div className="planner-course-list">{r.options.map(code=>courses.find(c=>c.code===code)).filter((c):c is CampusCourse=>!!c).map(c=><CourseRow key={c.code} course={c} p={p} status={status(c.code)} saving={saving} update={update} changeStatus={changeStatus}/>)}</div></div></details>)}
 {id==='gatech'&&!pair&&<p className="planner-empty">Select a Thread combination above to see your remaining courses.</p>}
 </section>:view==='Other requirements'?<section className="graduation-panel"><h2>Other degree requirements</h2><form className="other-credits" onSubmit={async e=>{e.preventDefault();await update({otherCredits:Number(other)})}}><label htmlFor="campus-credits">Other earned degree credits</label><p>Include accepted credits not marked completed here. Count each credit once.</p><div><input id="campus-credits" type="number" min="0" max="250" step="0.5" required value={other} onChange={e=>setOther(e.target.value)}/><button className="secondary" disabled={saving||Number(other)===p.otherCredits}>Save credits</button></div></form>
 <h3>Beyond this course audit</h3>{audit.notes.map(n=><p key={n}>{n}</p>)}
 {pair&&<OutLink href={pair.source}>Selected Thread curriculum & footnotes</OutLink>}
 </section>:<><div className="planner-filters"><div className="search"><Search size={16}/><input aria-label="Search courses" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search course, topic, or area"/></div><select aria-label="Course status filter" value={filter} onChange={e=>setFilter(e.target.value)}>{['All statuses',...statuses].map(s=><option key={s}>{s}</option>)}</select></div><div className="result-meta"><span>{visible.length} courses</span><span>Expand for details and credits</span></div><div className="planner-course-list">{visible.map(c=><CourseRow key={c.code} course={c} p={p} status={status(c.code)} saving={saving} update={update} changeStatus={changeStatus}/>)}{!visible.length&&<p className="planner-empty">No courses match these filters.</p>}</div></>}
 {progress.unknownCredits>0&&<p className="notice">{progress.unknownCredits} completed course(s) need awarded credits. Expand them to enter the credits on your record.</p>}
 <details className="compact-details planner-sources"><summary>Planner scope & sources</summary><p>{program.scope}</p><p>Checked October 1, 2026. Course catalog entries are not live availability or automatic elective approvals. This planner does not evaluate grades, prerequisites, substitutions or residency. Your catalog year and degree audit control eligibility.</p><OutLink href={program.source}>Official degree requirements</OutLink></details></div>
}
function CourseRow({course:c,p,status,saving,update,changeStatus}:{course:CampusCourse;p:CampusPlan;status:Status;saving:boolean;update:(p:Partial<CampusPlan>)=>Promise<boolean>;changeStatus:(code:string,status:Status)=>Promise<boolean>}){
 const [credits,setCredits]=useState(String(p.creditOverrides[c.code]??c.credits??''));
 return <article className={'planner-course '+(status==='Completed'?'course-complete':'')}><details><summary><span className="course-code mono">{c.code}</span><strong>{c.title}</strong><small>{c.credits===null?'Enter credits':`${c.credits} credits`}</small></summary><div className="planner-course-details"><p>{c.category}</p>{c.note&&<p>{c.note}</p>}<form className="awarded-credits" onSubmit={e=>{e.preventDefault();update({creditOverrides:{...p.creditOverrides,[c.code]:Number(credits)}})}}><label>Credits awarded<input aria-label={'Credits awarded for '+c.code} type="number" min="0" max="12" step="0.5" required value={credits} onChange={e=>setCredits(e.target.value)}/></label><button className="secondary" disabled={saving||credits===''||Number(credits)===(p.creditOverrides[c.code]??c.credits)}>Save</button></form><small>Count accepted degree credits once. Enter 0 for duplicate or non-degree credit.</small><OutLink href={c.source}>Course source</OutLink></div></details><select aria-label={'Status for '+c.code} disabled={saving} value={status} onChange={e=>changeStatus(c.code,e.target.value as Status)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></article>
}
