export const projects=[
{id:'local-first',title:'A local-first study planner',category:'Full stack',level:'Beginner',time:'1–2 weeks',description:'A study plan that keeps working when the Wi-Fi does not.',stack:['TypeScript','IndexedDB','React'],learn:'State modeling · offline storage · accessibility',brief:['Create courses and attach assignments with due dates.','Build an accessible weekly agenda with keyboard navigation.','Store changes offline and show when they were last saved.','Add export and import, then test a lost-connection scenario.'],stretch:'Add conflict resolution when two devices edit the same assignment.',deliverable:'A deployed app, a short demo, and a README explaining the data model.'},
{id:'search',title:'Search your own bookshelf',category:'AI & data',level:'Intermediate',time:'2–3 weeks',description:'A small search engine that finds passages, not just keywords.',stack:['Python','SQLite','Embeddings'],learn:'Retrieval · evaluation · information architecture',brief:['Index a set of public-domain texts with source metadata.','Start with keyword search to establish a baseline.','Add vector search and return the original passage with each hit.','Build 20 queries with expected answers and compare both methods.'],stretch:'Add hybrid ranking and report which queries it improves.',deliverable:'A reproducible evaluation and a demo with clickable source passages.'},
{id:'http',title:'An HTTP server from scratch',category:'Systems',level:'Intermediate',time:'2–3 weeks',description:'Understand what happens between a request and a response.',stack:['Go or Rust','TCP','HTTP'],learn:'Networking · parsing · concurrency',brief:['Accept a TCP connection and parse a minimal HTTP request.','Return static files with correct status and content headers.','Handle multiple clients and reject unsafe file paths.','Add integration tests for malformed requests and timeouts.'],stretch:'Implement keep-alive and compare throughput before and after.',deliverable:'A working server, protocol tests, and a documented benchmark.'},
{id:'budget',title:'Where did the money go?',category:'Full stack',level:'Beginner',time:'1–2 weeks',description:'Turn a messy expense CSV into an understandable monthly budget.',stack:['React','CSV','Charts'],learn:'Data cleaning · visualization · privacy',brief:['Import and validate a CSV without sending it to a server.','Let users categorize ambiguous transactions.','Show monthly totals with accessible text summaries.','Export a cleaned CSV and explain unsupported formats.'],stretch:'Add rule-based categorization with an undo history.',deliverable:'An interactive demo with synthetic sample data and an import guide.'},
{id:'queue',title:'A reliable background job queue',category:'Systems',level:'Advanced',time:'3–4 weeks',description:'Make background work survive failures, retries, and restarts.',stack:['TypeScript','PostgreSQL','Docker'],learn:'Distributed systems · idempotency · observability',brief:['Persist jobs and claim them atomically from two workers.','Add retry limits, exponential backoff, and a dead-letter state.','Handle a worker crashing midway through a job.','Instrument queue depth, attempts, and execution latency.'],stretch:'Add scheduled jobs and cancellation with documented guarantees.',deliverable:'A fault-injection demo and a write-up of delivery semantics.'},
{id:'campus',title:'Find a quiet place on campus',category:'Mobile & web',level:'Intermediate',time:'2–3 weeks',description:'Help students discover study spaces that match how they work.',stack:['React','Maps','SQL'],learn:'Geospatial queries · moderation · user research',brief:['Model spaces, accessibility features, hours, and noise level.','Build a list view that works without a map.','Collect feedback from three students and revise your filters.','Add an authenticated suggestion flow with moderation.'],stretch:'Add occupancy estimates with explicit confidence and timestamps.',deliverable:'A campus pilot, user research notes, and a documented moderation flow.'}
];
export const aiTools=[
{name:'Cursor',initial:'Cu',category:'Coding',url:'https://cursor.com/',description:'An AI-powered coding environment with codebase-aware assistance and agents.',use:'Explore an unfamiliar repository, draft a change, and review the diff.',check:'Run tests and inspect every change. A plausible implementation can still break an invariant.'},
{name:'GitHub Copilot',initial:'Co',category:'Coding',url:'https://github.com/features/copilot',description:'Coding assistance and agent workflows integrated with GitHub and development tools.',use:'Draft repetitive code or ask for an explanation of a function.',check:'Check dependency names, licensing context, and edge cases before accepting suggestions.'},
{name:'Claude',initial:'Cl',category:'Thinking & writing',url:'https://claude.com/product/overview',description:'A conversational assistant for reasoning, writing, document analysis, and coding.',use:'Ask for feedback on your own explanation or compare approaches to a problem.',check:'Verify factual claims and citations. Ask for hints before solutions when learning.'},
{name:'Gemini Notebook',initial:'Nb',category:'Research',url:'https://notebook.google/',description:'Google’s source-focused research and study workspace, formerly NotebookLM.',use:'Work through a reading collection and trace an answer back to a source.',check:'Read the cited passage in context. A source-grounded summary can still leave out nuance.'},
{name:'Perplexity',initial:'Pe',category:'Research',url:'https://www.perplexity.ai/',description:'An AI search and research tool that presents answers with source links.',use:'Find starting points for a topic, then read the original material.',check:'Confirm dates and open the sources. A linked citation does not guarantee the claim is supported.'}
];
export const colleges:{[key:string]:{source:string;description:string;courses:[string,string,string][]}}={
'Rutgers–New Brunswick':{source:'https://www.cs.rutgers.edu/academics/undergraduate/cs-degrees/b-s-degree',description:'Computer Science · B.S. core & selected electives',courses:[['01:198:111','Introduction to Computer Science','CS core'],['01:198:112','Data Structures','CS core'],['01:198:205','Introduction to Discrete Structures I','CS core'],['01:198:206','Introduction to Discrete Structures II','CS core'],['01:198:211','Computer Architecture','CS core'],['01:198:344','Design and Analysis of Computer Algorithms','CS core'],['01:640:151','Calculus I for the Mathematical and Physical Sciences','Math core'],['01:640:152','Calculus II for the Mathematical and Physical Sciences','Math core'],['01:640:250','Introductory Linear Algebra','Math core'],['01:198:213','Software Methodology','Elective'],['01:198:214','Systems Programming','Elective'],['01:198:336','Principles of Information and Data Management','Elective'],['01:198:352','Internet Technology','Elective'],['01:198:416','Operating Systems Design','Elective'],['01:198:440','Introduction to Artificial Intelligence','Elective']]}
};
export const problems=[
{id:'pair-sum',name:'Pair sum',level:'Easy',topic:'Arrays · Hash maps',prompt:'Given an array of integers and a target, return the indices of two distinct elements that add up to the target. Exactly one valid pair exists. Return the smaller index first.',signature:'function solve(nums, target) {\n  // Return [firstIndex, secondIndex]\n  \n}',example:'solve([2, 7, 11, 15], 9) → [0, 1]',hint:'As you scan the array, store the values you have seen and their indices.',tests:[{args:[[2,7,11,15],9],expected:[0,1]},{args:[[3,2,4],6],expected:[1,2]},{args:[[3,3],6],expected:[0,1]},{args:[[-2,5,8],6],expected:[0,2]}]},
{id:'balanced',name:'Balanced brackets',level:'Easy',topic:'Stacks · Strings',prompt:'Given a string containing only (), [], and {}, return true if the brackets are correctly matched and nested. An empty string is balanced.',signature:'function solve(s) {\n  // Return a boolean\n  \n}',example:'solve("([])") → true',hint:'A stack lets you compare each closing bracket with the most recent opening bracket.',tests:[{args:['([])'],expected:true},{args:['([)]'],expected:false},{args:[''],expected:true},{args:['{[()]}'],expected:true},{args:['(('],expected:false}]},
{id:'unique',name:'First unique character',level:'Easy',topic:'Strings · Counting',prompt:'Return the index of the first character that appears exactly once in the input string, or -1 if none exists. The input contains lowercase English letters only.',signature:'function solve(s) {\n  // Return the first unique index, or -1\n  \n}',example:'solve("swiss") → 1',hint:'Count occurrences first, then scan in the original order.',tests:[{args:['swiss'],expected:1},{args:['aabb'],expected:-1},{args:[''],expected:-1},{args:['leetcode'],expected:0},{args:['aabccd'],expected:2}]},
{id:'max-segment',name:'Largest contiguous sum',level:'Medium',topic:'Arrays · Dynamic programming',prompt:'Given a nonempty integer array, return the largest sum of a contiguous, nonempty subarray.',signature:'function solve(nums) {\n  // Return the largest sum\n  \n}',example:'solve([-2,1,-3,4,-1,2,1,-5,4]) → 6',hint:'At each element, decide whether to extend the previous segment or start again.',tests:[{args:[[-2,1,-3,4,-1,2,1,-5,4]],expected:6},{args:[[-4,-2,-7]],expected:-2},{args:[[1]],expected:1},{args:[[5,-1,3]],expected:7}]},
{id:'binary-search',name:'Find the insertion point',level:'Easy',topic:'Binary search',prompt:'Given a sorted array of distinct integers, return the index of target if present. Otherwise return the index where it should be inserted to keep the array sorted.',signature:'function solve(nums, target) {\n  // Return an index\n  \n}',example:'solve([1,3,5,6], 2) → 1',hint:'Keep a half-open search interval. The first element not smaller than target is your answer.',tests:[{args:[[1,3,5,6],2],expected:1},{args:[[1,3,5,6],7],expected:4},{args:[[],4],expected:0},{args:[[1,3,5],3],expected:1}]},
{id:'merge',name:'Merge overlapping intervals',level:'Medium',topic:'Sorting · Intervals',prompt:'Given intervals [start, end], merge all overlapping or touching intervals and return them in ascending order by start. Return an empty array for empty input.',signature:'function solve(intervals) {\n  // Return merged intervals\n  \n}',example:'solve([[1,3],[2,6],[8,10]]) → [[1,6],[8,10]]',hint:'Sort by start, then compare each interval with the end of the last merged interval.',tests:[{args:[[[1,3],[2,6],[8,10]]],expected:[[1,6],[8,10]]},{args:[[[1,4],[4,5]]],expected:[[1,5]]},{args:[[]],expected:[]},{args:[[[5,7],[1,8]]],expected:[[1,8]]}]}
];
