'use client';
import {useEffect,useState} from 'react';
import {Search,Check} from 'lucide-react';
import {type SavedState,OutLink} from './workspace';
import {courses,courseKey,courseStatus,degreeProgress,emptyPlanner,sequences,graduationChecks,type Planner,type Course,type CourseStatus} from './rutgers-courses';
const statuses:CourseStatus[]=['Not started','Planned','In progress','Completed'];
type Props={state:SavedState;save:(state:SavedState)=>Promise<boolean>;saving:boolean};
export default function CoursePlanner({state,save,saving}:Props){
 const p={...emptyPlanner,...state.planner};const progress=degreeProgress(state.courses,p);
 const [view,setView]=useState('Core'),[query,setQuery]=useState(''),[department,setDepartment]=useState('All departments'),[status,setStatus]=useState('All statuses'),[other,setOther]=useState(String(p.otherCredits));
 useEffect(()=>setOther(String(state.planner?.otherCredits||0)),[state.planner?.otherCredits]);
 const update=(patch:Partial<Planner>)=>save({...state,planner:{...p,...patch}});
 function changeStatus(code:string,value:CourseStatus){const next={...p.statuses};delete next[code];if(value==='Planned'||value==='In progress')next[code]=value;return save({...state,courses:[...state.courses.filter(c=>c!==courseKey(code)),...(value==='Completed'?[courseKey(code)]:[])],planner:{...p,statuses:next}})}
 const sequence=sequences.find(s=>s.id===p.science)||sequences[0];
 const visible=courses.filter(c=>view==='Core'?c.category.endsWith('core'):view==='Electives'?c.category==='Elective':view==='Science'?sequence.codes.includes(c.code):false).filter(c=>(department==='All departments'||view!=='Electives'||c.department===department)&&(status==='All statuses'||courseStatus(c.code,state.courses,p)===status)&&`${c.code} ${c.title} ${c.description}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="degree-planner"><div className="planner-header"><span>Rutgers–New Brunswick · School of Arts and Sciences</span><label>Degree<select aria-label="CS degree" disabled={saving} value={p.degree} onChange={e=>update({degree:e.target.value as Planner['degree']})}><option value="BS">B.S. Computer Science</option><option value="BA">B.A. Computer Science</option></select></label></div>
 <div className="degree-metrics"><div><span>Degree credits</span><strong>{progress.creditPercent}%</strong><progress aria-label="Degree credit progress" max={120} value={Math.min(progress.credits,120)}/><small>{progress.credits} / 120 earned · {Math.max(0,120-progress.credits)} remaining</small></div><div><span>CS major checklist</span><strong>{progress.majorPercent}%</strong><progress aria-label="CS major progress" max={100} value={progress.majorPercent}/><small>Core, elective distribution{p.degree==='BS'?', science':''}, and CS residency</small></div><div><span>Your courses</span><strong>{progress.completed}<em> completed</em></strong><small>{progress.inProgress} in progress · {progress.planned} planned</small><button className="text-link" onClick={()=>{setView('Graduation');setQuery('');setStatus('All statuses')}}>Add other earned credits</button></div></div>
 <p className="planner-caption">Percentages use completed courses. Credit progress is separate from graduation eligibility; finish the requirements under Graduation too.</p>
 <div className="planner-tabs" role="group" aria-label="Course planner sections">{['Core','Electives','Science','Graduation'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>{setView(v);setQuery('');setStatus('All statuses')}}>{v}{v==='Electives'&&<span>55</span>}</button>)}</div>
 {view==='Graduation'?<section className="graduation-panel"><h2>Credits & graduation requirements</h2><form className="other-credits" onSubmit={e=>{e.preventDefault();update({otherCredits:Number(other)})}}><label htmlFor="other-credits">Other earned degree credits</label><p>Enter credits from courses not marked completed in this planner, including other Core, minor, or accepted AP/transfer credits. Count each credit once.</p><div><input id="other-credits" type="number" min="0" max="250" step="0.5" required value={other} onChange={e=>setOther(e.target.value)}/><button className="secondary" disabled={saving||Number(other)===p.otherCredits}>Save credits</button></div></form>
 <div className="requirement-lines"><Requirement label="Degree credits" done={progress.credits>=120} value={`${progress.credits} / 120`}/><Requirement label="CS core" done={progress.csCore===6} value={`${progress.csCore} / 6`}/><Requirement label="Math core" done={progress.mathCore===3} value={`${progress.mathCore} / 3`}/><Requirement label="Approved elective slots" done={progress.electives===progress.target} value={`${progress.electives} / ${progress.target}`}/><Requirement label="Electives taken in NB Computer Science" done={progress.nbElectives>=progress.nbTarget} value={`${Math.min(progress.nbElectives,progress.nbTarget)} / ${progress.nbTarget}`}/><Requirement label="NB CS electives at 300 level or above" done={progress.upper>=2} value={`${Math.min(progress.upper,2)} / 2`}/><Requirement label="Required/elective CS courses taken at NB" done={progress.nbCount>=7} value={`${Math.min(progress.nbCount,7)} / 7`}/>{p.degree==='BS'&&<Requirement label="One complete science sequence" done={progress.scienceComplete} value={progress.scienceComplete?'Complete':'Not complete'}/>}</div>
 <h3>Confirm against your degree audit</h3><p className="planner-caption">Check these after verifying your record. Core courses may also satisfy your major, but their credits count only once.</p><div className="graduation-checks">{graduationChecks.map(([id,title,description])=><label key={id}><input type="checkbox" checked={p.checks.includes(id)} disabled={saving} onChange={e=>update({checks:e.target.checked?[...p.checks,id]:p.checks.filter(c=>c!==id)})}/><span><strong>{title}</strong><small>{description}</small></span></label>)}</div><p className="source-note">{p.checks.length} / {graduationChecks.length} confirmations saved. This planner estimates progress; Rutgers certifies your degree.</p></section>:<>
 {view==='Core'&&<div className="requirement-strip"><span>CS core <b>{progress.csCore}/6</b></span><span>Math core <b>{progress.mathCore}/3</b></span></div>}
 {view==='Electives'&&<><div className="requirement-strip"><span>Elective slots <b>{progress.electives}/{progress.target}</b></span><span>NB CS <b>{Math.min(progress.nbElectives,progress.nbTarget)}/{progress.nbTarget}</b></span><span>NB CS, 300+ <b>{Math.min(progress.upper,2)}/2</b></span></div><p className="planner-caption">Choose {progress.target} approved electives, including at least {progress.nbTarget} taken in NB CS and two of those at 300 level or above. At most one approved CS 493/494 counts. The list below includes every course on the department’s current approved list.</p></>}
 {view==='Science'&&<><label className="science-picker">Science sequence<select aria-label="Science sequence" disabled={saving} value={sequence.id} onChange={e=>update({science:e.target.value})}>{sequences.map(s=><option key={s.id} value={s.id}>{s.name} · {s.codes.length} courses</option>)}</select></label><p className="planner-caption">{p.degree==='BS'?'Complete any one of these eight accepted sequences, including its labs. Courses from different sequences do not combine into a completed sequence.':'The CS B.A. does not require a science sequence. These courses may still apply to degree credits and SAS Core.'} Changing this view keeps all saved course statuses.</p><div className="requirement-strip">{progress.science.filter(s=>s.done>0).map(s=><span key={s.id}>{s.name} <b>{s.done}/{s.codes.length}</b></span>)}</div></>}
 <div className="planner-filters"><div className="search"><Search size={16}/><input aria-label="Search courses" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search courses or topics"/></div>{view==='Electives'&&<select aria-label="Course department" value={department} onChange={e=>setDepartment(e.target.value)}><option>All departments</option>{[...new Set(courses.filter(c=>c.category==='Elective').map(c=>c.department))].map(d=><option key={d}>{d}</option>)}</select>}<select aria-label="Course status filter" value={status} onChange={e=>setStatus(e.target.value)}>{['All statuses',...statuses].map(s=><option key={s}>{s}</option>)}</select></div>
 <div className="result-meta"><span>{visible.length} courses</span><span>Expand a course for details</span></div><div className="planner-course-list">{visible.map(c=><CourseRow key={c.code} course={c} p={p} status={courseStatus(c.code,state.courses,p)} saving={saving} update={update} changeStatus={changeStatus}/>)}{!visible.length&&<p className="planner-empty">No courses match these filters.</p>}</div>
 </>}
 {progress.unknownCredits>0&&<p className="notice">{progress.unknownCredits} completed independent-study course(s) need awarded credits. Expand the course to enter them.</p>}
 <details className="compact-details planner-sources"><summary>Requirements, counting rules & sources</summary><p>Catalog checked September 29, 2026. Course descriptions are summaries; semester offerings and section prerequisites can change. This catalog is not a live registration schedule. Older catalog versions can differ; approved substitutions need an advisor’s review.</p><p>Major progress counts nine core courses, the required elective slots, CS residency, and (for the B.S.) one science sequence. Extra electives cannot replace missing core courses. Transfer/AP courses count toward the course checklist only when Rutgers has awarded the corresponding equivalency; mark them as transfer/AP to exclude them from NB residency. Adjust awarded credits for duplicate-credit exclusions. Required/elective CS residency needs seven courses taken in NB CS. Prerequisites need C or better; no more than one D is allowed in the major.</p><div className="source-links"><OutLink href="https://www.cs.rutgers.edu/academics/undergraduate/cs-degrees/b-s-degree">CS B.S.</OutLink><OutLink href="https://www.cs.rutgers.edu/academics/undergraduate/cs-degrees/b-a-degree">CS B.A.</OutLink><OutLink href="https://www.cs.rutgers.edu/academics/undergraduate/electives">Approved electives</OutLink><OutLink href="https://sasundergrad.rutgers.edu/majors-and-core-curriculum/degree-requirements">SAS degree requirements</OutLink><OutLink href="https://sasundergrad.rutgers.edu/majors-and-core-curriculum/core">SAS Core</OutLink><OutLink href="https://www.sasundergrad.rutgers.edu/resources/policies/rutgers-university-guideline/credits-and-residency">Credits & residency</OutLink></div></details>
 </div>;
}
function Requirement({label,done,value}:{label:string;done:boolean;value:string}){return <div><span>{label}</span><strong className={done?'requirement-done':''}>{done&&<Check size={14}/>} {value}</strong></div>}
function CourseRow({course:c,p,status,saving,update,changeStatus}:{course:Course;p:Planner;status:CourseStatus;saving:boolean;update:(p:Partial<Planner>)=>Promise<boolean>;changeStatus:(code:string,status:CourseStatus)=>Promise<boolean>}){const [credits,setCredits]=useState(String(p.creditOverrides[c.code]??c.credits??''));useEffect(()=>setCredits(String(p.creditOverrides[c.code]??c.credits??'')),[p.creditOverrides,c.code,c.credits]);return <article className={'planner-course '+(status==='Completed'?'course-complete':'')}><details><summary><span className="course-code mono">{c.code}</span><strong>{c.title}</strong><small>{c.credits===null?'Variable credits':`${c.credits} credits`}</small></summary><div className="planner-course-details"><p>{c.description}</p><p><b>Prerequisites:</b> {c.prerequisites}</p>{c.offering&&<p><b>Typical offering:</b> {c.offering}. Not a live schedule.</p>}<p><b>Department:</b> {c.department}</p><label className="inline-check"><input type="checkbox" disabled={saving} checked={p.transfer.includes(c.code)} onChange={e=>update({transfer:e.target.checked?[...p.transfer,c.code]:p.transfer.filter(code=>code!==c.code)})}/>Accepted transfer/AP equivalency (not taken at Rutgers–NB)</label>{c.independent&&<label className="inline-check"><input type="checkbox" disabled={saving} checked={p.approvedIndependent.includes(c.code)} onChange={e=>update({approvedIndependent:e.target.checked?[...p.approvedIndependent,c.code]:p.approvedIndependent.filter(code=>code!==c.code)})}/>Department approved this independent study for elective credit</label>}<form className="awarded-credits" onSubmit={e=>{e.preventDefault();update({creditOverrides:{...p.creditOverrides,[c.code]:Number(credits)}})}}><label>Credits awarded<input aria-label={'Credits awarded for '+c.code} type="number" min="0" max="12" step="0.5" required value={credits} onChange={e=>setCredits(e.target.value)}/></label><button className="secondary" disabled={saving||credits===''||Number(credits)===(p.creditOverrides[c.code]??c.credits)}>Save</button></form><small>Use the credits on your record; enter 0 for duplicate credit. Count accepted AP/transfer credits here or in “Other earned credits,” never both.</small><OutLink href={c.source}>Course source</OutLink></div></details><select aria-label={'Status for '+c.code} disabled={saving} value={status} onChange={e=>changeStatus(c.code,e.target.value as CourseStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></article>;}
