'use client';
import {useState} from 'react';
import videoMetadata from './video-metadata.json';
import {Play,Bookmark,ArrowUpRight} from 'lucide-react';
import {Picker,OutLink,type SavedState} from './workspace';
type Tutorial={id:string;title:string;creator:string;level:string;stack:string;description:string;prerequisites:string;exercise:string;chapters?:[string,number][]};
const builds:Tutorial[]=[
 {id:'-42K44A1oMA',title:'Build a full-stack bookstore',creator:'freeCodeCamp · DevEmpower',level:'Intermediate',stack:'React / Express / MongoDB',description:'A complete MERN walkthrough: build an API, connect MongoDB, then create the React screens for adding, editing, and deleting books.',prerequisites:'JavaScript functions, React components, Node.js and npm installed.',exercise:'Add search and pagination. Write API tests for invalid input and missing books, then explain the data model in your README.',chapters:[['Node & Express',70],['MongoDB',361],['React app',1521],['Create a book',2342]]},
 {id:'8ext9G7xspg',title:'12 beginner Python projects',creator:'freeCodeCamp · Kylie Ying',level:'Beginner',stack:'Python / command line',description:'Practice Python by making small programs and games, including guessing games, rock-paper-scissors, and hangman.',prerequisites:'Basic variables, loops and functions; Python installed on your computer.',exercise:'Choose one game. Add input validation, save a high score to a file, and test the game logic separately from terminal input.'},
 {id:'jFfo23yIWac',title:'Learn Go by building 11 projects',creator:'freeCodeCamp',level:'Intermediate',stack:'Go / APIs / databases',description:'Move from a web server to backend projects, including CRUD APIs and database-backed applications.',prerequisites:'Comfort with one programming language and HTTP basics; a Go development environment.',exercise:'Pick one API. Add table-driven tests and consistent JSON errors, then document example requests in the README.'}
];
const lessons:Tutorial[]=[
 {id:'6eBSHbLKuN0',title:'Mastering Claude Code in 30 minutes',creator:'Anthropic',level:'Start here',stack:'Terminal / repository workflow',description:'Watch Claude Code used inside a real development workflow. Start with understanding a repository before asking it to change code.',prerequisites:'A small Git repository and Claude Code access. Use the current setup guide above before following the video.',exercise:'Ask Claude to map your repository and identify the test command. Pick one function and explain its behavior yourself before requesting an edit.'},
 {id:'gv0WHhKelSE',title:'Claude Code best practices',creator:'Anthropic · Code w/ Claude',level:'Next step',stack:'Planning / context / review',description:'A workshop on working effectively with Claude Code: supplying context, planning changes, and keeping the iteration focused.',prerequisites:'Finish one Claude Code session and know how to inspect a Git diff.',exercise:'Write a short CLAUDE.md with the real build and test commands. Ask for a plan for one small bug, implement it, and review every changed file.'},
 {id:'gh2_PhgZGsM',title:'Claude Code for Beginners — full course',creator:'freeCodeCamp',level:'Deep dive',stack:'Setup / tests / debugging',description:'A longer, hands-on course covering the first session, codebase exploration, project building, unit tests, and larger editing tasks.',prerequisites:'Basic terminal and Git skills. Follow the chapters in a disposable practice repository.',exercise:'Use the unit-testing chapter to create a regression test for a bug. Verify that it fails before the fix and passes afterward.',chapters:[['Setup',30],['First session',565],['Explore a codebase',1438],['Unit tests',3409]]}
];
function Video({tutorial:t}:{tutorial:Tutorial}){const [start,setStart]=useState<number|null>(null);const [imageFailed,setImageFailed]=useState(false);const meta=videoMetadata[t.id as keyof typeof videoMetadata];return <div className="lesson-video">{start===null?<button className="video-cover" onClick={()=>setStart(0)} aria-label={'Play '+t.title}><span className="video-channel">{t.creator}</span>{!imageFailed&&<img className="video-thumbnail" src={meta.thumbnail_url} alt="" loading="lazy" onError={()=>setImageFailed(true)}/>}<span className="video-play"><Play size={27}/></span><strong className={imageFailed?'':'sr-only'}>{t.title}</strong><span className="video-caption">Watch the tutorial</span></button>:<iframe key={start} title={t.title} src={`https://www.youtube-nocookie.com/embed/${t.id}?start=${start}&autoplay=1`} allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>}{t.chapters&&<div className="chapter-links">{t.chapters.map(([label,seconds])=><button key={seconds} onClick={()=>setStart(seconds)}><span>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</span>{label}</button>)}</div>}<a className="out-link video-fallback" href={'https://www.youtube.com/watch?v='+t.id} target="_blank" rel="noreferrer">Open on YouTube <ArrowUpRight size={14}/></a></div>}
export function TutorialLibrary({kind,state,save,saving}:{kind:string;state:SavedState;save:(s:SavedState)=>Promise<boolean>;saving:boolean}){const ai=kind==='ai-literacy';const [filter,setFilter]=useState('All tutorials');const tutorials=ai?lessons:builds;const shown=tutorials.filter(t=>filter!=='Saved tutorials'||state.projects.includes(t.id));return <>
 {ai&&<div className="learning-guide"><div><span className="eyebrow">CLAUDE CODE / LEARNING PATH</span><h2>From your first session to a reviewed change.</h2><p>Start with the short introduction, try the exercise, then move to the workshop. The videos are free; Claude Code access depends on your Anthropic plan or API billing.</p></div><div className="guide-links"><OutLink href="https://code.claude.com/docs/en/quickstart">Current installation guide</OutLink><OutLink href="https://code.claude.com/docs/en/best-practices">Official workflow reference</OutLink><p>Follow current docs for setup; interfaces and commands may differ from older recordings.</p></div></div>}
 <div className="library-intro"><span>{ai?'Three lessons. A real exercise after each.':'Complete build videos · Beginner to intermediate'}</span><Picker label="Tutorial filter" value={filter} onChange={setFilter} options={['All tutorials','Saved tutorials']}/></div>
 <div className="tutorial-list">{shown.map((t,i)=><article className="tutorial" key={t.id}><Video tutorial={t}/><div className="tutorial-copy"><div className="card-top"><span className="mono">{String(tutorials.indexOf(t)+1).padStart(2,'0')} / {t.level}</span><button className="icon-button" disabled={saving} aria-label={(state.projects.includes(t.id)?'Unsave ':'Save ')+t.title} onClick={()=>save({...state,projects:state.projects.includes(t.id)?state.projects.filter(id=>id!==t.id):[...state.projects,t.id]})}><Bookmark size={18} fill={state.projects.includes(t.id)?'currentColor':'none'}/></button></div><h2>{t.title}</h2><p className="tutorial-byline">{t.creator} · {t.stack}</p><p>{t.description}</p><h3>Before you start</h3><p>{t.prerequisites}</p><div className="practice-assignment"><h3>{ai?'Try it yourself':'Make it your own'}</h3><p>{t.exercise}</p></div></div></article>)}</div>{!shown.length&&<div className="notice">No saved tutorials here yet. Use the bookmark beside a lesson to keep it.</div>}
 <p className="source-note">Videos link to their original creators on YouTube. If playback is unavailable here, use “Open on YouTube.” Reviewed September 28, 2026.</p>
 </>}
const clubs=[
 {name:'USACS',full:'Undergraduate Student Alliance of Computer Scientists',focus:'CS community & mentorship',description:'Technical workshops, peer mentorship, and a place to meet other Rutgers students working on software.',join:'Visit the club website for its community links and upcoming events.',url:'https://usacs.cs.rutgers.edu/'},
 {name:'WiCS',full:'Women in Computer Science',focus:'Community & career development',description:'Mentorship, technical talks, career events, and HackHERS. Membership is open to all Rutgers students.',join:'Use the newsletter and event links on the WiCS website to get involved.',url:'https://rutgerswics.org/'},
 {name:'RUMAD',full:'Rutgers University Mobile App Development',focus:'Team projects & mobile apps',description:'Learn through the beginner Accelerator program or collaborate on an app through the Incubator program.',join:'Read the current program details and application updates on the club website.',url:'https://rumad.club/'},
 {name:'HackRU',full:'Rutgers student hackathon',focus:'Hackathons & building together',description:'Build a project with a team, meet other developers, and take part in the Rutgers hackathon community.',join:'Check the official site for the next event, registration, and organizer opportunities.',url:'https://hackru.org/'},
 {name:'SLUG',full:'Student Linux Users Group',focus:'Linux & open source',description:'A community for students interested in Linux, free software, and learning how their systems work.',join:'Find the current community and meeting information through SLUG’s website.',url:'https://ruslug.org/'},
 {name:'Rutgers AI',full:'Rutgers Artificial Intelligence Club',focus:'AI learning & projects',description:'Meet students interested in artificial intelligence and explore workshops and collaborative projects.',join:'Use the official getINVOLVED organization listing to find contact and membership information.',url:'https://rutgers.campuslabs.com/engage/organization/ruai'}
];
export function Clubs({college}:{college:string}){return <><div className="directory-note"><div><span className="eyebrow">{college}</span><p>Six starting points for finding your CS community.</p><span>Check each organization for current meetings and recruitment dates.</span></div><OutLink href="https://spec.cs.rutgers.edu/clubs/">CS department directory</OutLink></div><div className="club-grid">{clubs.map((club,i)=><article className="club-card" key={club.name}><div className="club-number mono">0{i+1} / {club.focus}</div><h2>{club.name}</h2><p className="club-full">{club.full}</p><p>{club.description}</p><h3>How to get involved</h3><p>{club.join}</p><OutLink href={club.url}>Visit {club.name}</OutLink></article>)}</div><p className="source-note">Selected from Rutgers’ official CS student organization directory. Reviewed September 28, 2026. This is a student guide, not an official university website.</p></>}
