'use client';
import {useState} from 'react';
import videoMetadata from './video-metadata.json';
import {Play,Bookmark,ArrowUpRight} from 'lucide-react';
import {Picker,OutLink,type SavedState} from './workspace';
type Tutorial={id:string;title:string;creator:string;level:string;stack:string;description:string;prerequisites:string;exercise:string;chapters?:[string,number][]};
const builds:Tutorial[]=[
 {id:'-42K44A1oMA',title:'Build a full-stack bookstore',creator:'freeCodeCamp · DevEmpower',level:'Intermediate',stack:'React / Express / MongoDB',description:'A complete MERN walkthrough: build an API, connect MongoDB, then create the React screens for adding, editing, and deleting books.',prerequisites:'JavaScript functions, React components, Node.js and npm installed.',exercise:'Add search and pagination. Write API tests for invalid input and missing books, then explain the data model in your README.',chapters:[['Node & Express',70],['MongoDB',361],['React app',1521],['Create a book',2342]]},
 {id:'8ext9G7xspg',title:'12 beginner Python projects',creator:'freeCodeCamp · Kylie Ying',level:'Beginner',stack:'Python / command line',description:'Practice Python by making small programs and games, including guessing games, rock-paper-scissors, and hangman.',prerequisites:'Basic variables, loops and functions; Python installed on your computer.',exercise:'Choose one game. Add input validation, save a high score to a file, and test the game logic separately from terminal input.'},
 {id:'jFfo23yIWac',title:'Learn Go by building 11 projects',creator:'freeCodeCamp',level:'Intermediate',stack:'Go / APIs / databases',description:'Move from a web server to backend projects, including CRUD APIs and database-backed applications.',prerequisites:'Comfort with one programming language and HTTP basics; a Go development environment.',exercise:'Pick one API. Add table-driven tests and consistent JSON errors, then document example requests in the README.'}
];
function Video({tutorial:t}:{tutorial:Tutorial}){const [start,setStart]=useState<number|null>(null);const [imageFailed,setImageFailed]=useState(false);const meta=videoMetadata[t.id as keyof typeof videoMetadata];return <div className="lesson-video">{start===null?<button className="video-cover" onClick={()=>setStart(0)} aria-label={'Play '+t.title}>{!imageFailed&&<img className="video-thumbnail" src={meta.thumbnail_url} alt="" loading="lazy" onError={()=>setImageFailed(true)}/>}<span className="video-play"><Play size={27}/></span><strong className={imageFailed?'':'sr-only'}>{t.title}</strong></button>:<iframe key={start} title={t.title} src={`https://www.youtube-nocookie.com/embed/${t.id}?start=${start}&autoplay=1`} allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>}{t.chapters&&<details className="video-chapters"><summary>Chapters</summary><div className="chapter-links">{t.chapters.map(([label,seconds])=><button key={seconds} onClick={()=>setStart(seconds)}><span>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</span>{label}</button>)}</div></details>}<a className="out-link video-fallback" href={'https://www.youtube.com/watch?v='+t.id} target="_blank" rel="noreferrer">Open on YouTube <ArrowUpRight size={14}/></a></div>}
export function TutorialLibrary({kind,state,save,saving}:{kind:string;state:SavedState;save:(s:SavedState)=>Promise<boolean>;saving:boolean}){const [filter,setFilter]=useState('All tutorials');const tutorials=builds;const shown=tutorials.filter(t=>filter!=='Saved tutorials'||state.projects.includes(t.id));return <>
 <div className="library-intro"><span/><Picker label="Tutorial filter" value={filter} onChange={setFilter} options={['All tutorials','Saved tutorials']}/></div>
 <div className="tutorial-list">{shown.map((t,i)=><article className="tutorial" key={t.id}><Video tutorial={t}/><div className="tutorial-copy"><div className="card-top"><span className="mono">{t.level}</span><button className="icon-button" disabled={saving} aria-label={(state.projects.includes(t.id)?'Unsave ':'Save ')+t.title} onClick={()=>save({...state,projects:state.projects.includes(t.id)?state.projects.filter(id=>id!==t.id):[...state.projects,t.id]})}><Bookmark size={18} fill={state.projects.includes(t.id)?'currentColor':'none'}/></button></div><h2>{t.title}</h2><p className="tutorial-byline">{t.creator} · {t.stack}</p><p>{t.description}</p><details className="compact-details"><summary>Prerequisites & exercise</summary><h3>Prerequisites</h3><p>{t.prerequisites}</p><div className="practice-assignment"><h3>Make it your own</h3><p>{t.exercise}</p></div></details></div></article>)}</div>{!shown.length&&<div className="notice">No saved tutorials here yet. Use the bookmark beside a lesson to keep it.</div>}
 
 </>}
const clubs=[
 {name:'USACS',full:'Undergraduate Student Alliance of Computer Scientists',focus:'CS community & mentorship',description:'Technical workshops, peer mentorship, and a place to meet other Rutgers students working on software.',join:'Visit the club website for its community links and upcoming events.',url:'https://usacs.cs.rutgers.edu/'},
 {name:'WiCS',full:'Women in Computer Science',focus:'Community & career development',description:'Mentorship, technical talks, career events, and HackHERS. Membership is open to all Rutgers students.',join:'Use the newsletter and event links on the WiCS website to get involved.',url:'https://rutgerswics.org/'},
 {name:'RUMAD',full:'Rutgers University Mobile App Development',focus:'Team projects & mobile apps',description:'Learn through the beginner Accelerator program or collaborate on an app through the Incubator program.',join:'Read the current program details and application updates on the club website.',url:'https://rumad.club/'},
 {name:'HackRU',full:'Rutgers student hackathon',focus:'Hackathons & building together',description:'Build a project with a team, meet other developers, and take part in the Rutgers hackathon community.',join:'Check the official site for the next event, registration, and organizer opportunities.',url:'https://hackru.org/'},
 {name:'SLUG',full:'Student Linux Users Group',focus:'Linux & open source',description:'A community for students interested in Linux, free software, and learning how their systems work.',join:'Find the current community and meeting information through SLUG’s website.',url:'https://ruslug.org/'},
 {name:'Rutgers AI',full:'Rutgers Artificial Intelligence Club',focus:'AI learning & projects',description:'Meet students interested in artificial intelligence and explore workshops and collaborative projects.',join:'Use the official getINVOLVED organization listing to find contact and membership information.',url:'https://rutgers.campuslabs.com/engage/organization/ruai'}
];
export function Clubs({college}:{college:string}){return <><div className="library-intro"><span>{college}</span><OutLink href="https://spec.cs.rutgers.edu/clubs/">Official directory</OutLink></div><div className="club-grid">{clubs.map((club,i)=><article className="club-card" key={club.name}><h2>{club.name}</h2><p className="club-full">{club.full}</p><p>{club.description}</p><OutLink href={club.url}>Visit {club.name}</OutLink></article>)}</div><p className="source-note">Unofficial student guide. Check club websites for meeting times.</p></>}
