'use client';
import {campusClubs} from './campus-clubs';
import {universities,isUniversity} from './university';
import {OutLink} from './workspace';
const clubs=[
 {name:'USACS',full:'Undergraduate Student Alliance of Computer Scientists',focus:'CS community & mentorship',description:'Technical workshops, peer mentorship, and a place to meet other Rutgers students working on software.',join:'Visit the club website for its community links and upcoming events.',url:'https://usacs.cs.rutgers.edu/'},
 {name:'WiCS',full:'Women in Computer Science',focus:'Community & career development',description:'Mentorship, technical talks, career events, and HackHERS. Membership is open to all Rutgers students.',join:'Use the newsletter and event links on the WiCS website to get involved.',url:'https://rutgerswics.org/'},
 {name:'RUMAD',full:'Rutgers University Mobile App Development',focus:'Team projects & mobile apps',description:'Learn through the beginner Accelerator program or collaborate on an app through the Incubator program.',join:'Read the current program details and application updates on the club website.',url:'https://rumad.club/'},
 {name:'HackRU',full:'Rutgers student hackathon',focus:'Hackathons & building together',description:'Build a project with a team, meet other developers, and take part in the Rutgers hackathon community.',join:'Check the official site for the next event, registration, and organizer opportunities.',url:'https://hackru.org/'},
 {name:'SLUG',full:'Student Linux Users Group',focus:'Linux & open source',description:'A community for students interested in Linux, free software, and learning how their systems work.',join:'Find the current community and meeting information through SLUG’s website.',url:'https://ruslug.org/'},
 {name:'Rutgers AI',full:'Rutgers Artificial Intelligence Club',focus:'AI learning & projects',description:'Meet students interested in artificial intelligence and explore workshops and collaborative projects.',join:'Use the official getINVOLVED organization listing to find contact and membership information.',url:'https://rutgers.campuslabs.com/engage/organization/ruai'}
];
export function Clubs({college}:{college:string}){const id=isUniversity(college)?universities[college].id:'rutgers';const data=campusClubs[id]||{source:'https://spec.cs.rutgers.edu/clubs/',clubs};return <><div className="library-intro"><span>{college}</span><OutLink href={data.source}>Official directory</OutLink></div><div className="club-grid">{data.clubs.map(club=><article className="club-card" key={club.name}><h2>{club.name}</h2><p className="club-full">{club.full}</p><p>{club.description}</p><OutLink href={club.url}>{club.url===data.source?'Directory & contact':'Visit '+club.name}</OutLink></article>)}</div><p className="source-note">Unofficial student guide. Check club websites for meeting times.</p></>}
