'use client';
import {useState,useRef} from 'react';
import {Play,Check,ArrowLeft} from 'lucide-react';
import {problems,languages,starter,example,listSource,canonicalProblemId,type Language} from './practice-data/catalog';
import type {SavedState} from './workspace';
import type {RunResult} from './practice-data/engine';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
export default function Practice({state,save,saving}:{state:SavedState;save:(s:SavedState)=>Promise<boolean>;saving:boolean}){
 const [selected,setSelected]=useState<string|null>(null),[language,setLanguage]=useState<Language>('javascript'),[code,setCode]=useState(''),[hint,setHint]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState<(RunResult&{diagnostics?:string})|null>(null),[runnerError,setRunnerError]=useState(''),[search,setSearch]=useState(''),[topic,setTopic]=useState('All topics'),[difficulty,setDifficulty]=useState('All difficulties'),[status,setStatus]=useState('All problems'),[tab,setTab]=useState('results');
 const drafts=useRef(new Map<string,string>());const problem=problems.find(p=>p.id===selected);const currentLanguage=languages.find(l=>l.id===language)!;
 const history=state.submissions.filter(s=>canonicalProblemId(s.problem)===selected),solved=new Set([...(state.practiceSolved||[]),...state.submissions.filter(s=>s.passed===s.total).map(s=>s.problem)].map(canonicalProblemId).filter(id=>problems.some(p=>p.id===id)));
 const visible=problems.filter(p=>(!search||p.name.toLowerCase().includes(search.toLowerCase()))&&(topic==='All topics'||p.topic===topic)&&(difficulty==='All difficulties'||p.level===difficulty)&&(status==='All problems'||(status==='Solved'===solved.has(p.id))));
 function choose(id:string,nextLanguage=language){if(selected)drafts.current.set(selected+':'+language,code);const p=problems.find(p=>p.id===id)!;setSelected(id);setLanguage(nextLanguage);setCode(drafts.current.get(id+':'+nextLanguage)??state.submissions.find(s=>canonicalProblemId(s.problem)===id&&(s.language||'javascript')===nextLanguage)?.code??starter(p,nextLanguage));setHint(false);setResult(null);setRunnerError('');setTab('results');}
 async function run(submit:boolean){if(!problem||busy)return;setBusy(true);setRunnerError('');setResult(null);setTab('results');const submittedCode=code,submittedProblem=problem.id,submittedLanguage=language;drafts.current.set(problem.id+':'+language,code);try{
  const response=await fetch('/api/practice/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({problem:submittedProblem,language:submittedLanguage,code:submittedCode,submit}),signal:AbortSignal.timeout(55000)});const output=await response.json() as RunResult & {diagnostics?:string;error?:string};if(!response.ok)throw Error(output.error||'The runner could not finish. Please retry.');setResult(output);
  if(submit){const saved=await save({...state,practiceSolved:output.passed===output.total?[...new Set([...solved,submittedProblem])]:state.practiceSolved,submissions:[{id:crypto.randomUUID(),problem:submittedProblem,language:submittedLanguage,code:submittedCode,passed:output.passed,total:output.total,date:new Date().toISOString()},...state.submissions].slice(0,200)});if(!saved)setRunnerError('Your results are shown below, but the submission could not be saved. Keep this page open and submit again.');}
 }catch(e){setRunnerError(e instanceof Error&&e.name==='TimeoutError'?'The runner timed out. Your code is still here; please retry.':(e as Error).message)}finally{setBusy(false)}}
 function back(){if(selected)drafts.current.set(selected+':'+language,code);setSelected(null)}
 return !problem?<>
  <div className="practice-summary"><p><strong>Blind 75</strong><span className="practice-count">{solved.size} / 75 solved</span></p></div>
  <div className="practice-filters"><input type="search" aria-label="Search problems" placeholder="Search problems" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter by topic" value={topic} onChange={e=>setTopic(e.target.value)}>{['All topics',...new Set(problems.map(p=>p.topic))].map(t=><option key={t}>{t}</option>)}</select><select aria-label="Filter by difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['All difficulties','Easy','Medium','Hard'].map(t=><option key={t}>{t}</option>)}</select><select aria-label="Filter by completion" value={status} onChange={e=>setStatus(e.target.value)}>{['All problems','Unsolved','Solved'].map(t=><option key={t}>{t}</option>)}</select></div>
  <div className="data-panel"><Table><TableHeader><TableRow><TableHead>STATUS</TableHead><TableHead>PROBLEM</TableHead><TableHead>DIFFICULTY</TableHead><TableHead/></TableRow></TableHeader><TableBody>{visible.map(p=><TableRow key={p.id}><TableCell>{solved.has(p.id)?<span aria-label="Solved"><Check size={18} className="green"/></span>:<span className="problem-number mono">{String(problems.indexOf(p)+1).padStart(2,'0')}</span>}</TableCell><TableCell><button className="problem-link" onClick={()=>choose(p.id)}>{p.name}</button><span className="problem-topic">{p.topic}</span></TableCell><TableCell><span className={'status '+(p.level==='Easy'?'status-offer':p.level==='Hard'?'status-rejected':'status-interviewing')}>{p.level}</span></TableCell><TableCell><button className="text-link" onClick={()=>choose(p.id)} aria-label={'Solve '+p.name}>Solve</button></TableCell></TableRow>)}{!visible.length&&<TableRow><TableCell colSpan={4}>No problems match these filters.</TableCell></TableRow>}</TableBody></Table></div>
  <p className="source-note">JavaScript · Python · Java · C++. <a href={listSource} target="_blank" rel="noreferrer">Blind 75 by Yangshun Tay</a>. Independently written prompts and practice cases.</p>
 </>:<>
  <button className="text-link back-link" disabled={busy} onClick={back}><ArrowLeft size={15}/>All problems</button>
  <div className="coding-layout"><div className="problem-panel"><span className={'status '+(problem.level==='Easy'?'status-offer':problem.level==='Hard'?'status-rejected':'status-interviewing')}>{problem.level}</span><h2>{problem.name}</h2><p>{problem.prompt}</p><h3>Example</h3><pre>{example(problem)}</pre><button className="text-link" onClick={()=>setHint(!hint)}>{hint?'Hide hint':'Hint'}</button>{hint&&<p className="hint">{problem.hint}</p>}<p className="source-note"><a href={'https://leetcode.com/problems/'+problem.id+'/'} target="_blank" rel="noreferrer">Original problem on LeetCode</a></p></div>
  <div className="editor-panel"><div className="editor-header"><span className="mono">{currentLanguage.file}</span><select aria-label="Programming language" value={language} disabled={busy} onChange={e=>choose(problem.id,e.target.value as Language)}>{languages.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><label className="sr-only" htmlFor="code-editor">Your {currentLanguage.name} solution</label><textarea id="code-editor" spellCheck={false} autoCapitalize="off" autoCorrect="off" value={code} maxLength={20000} disabled={busy} onChange={e=>setCode(e.target.value)} onKeyDown={e=>{if(e.key==='Tab'){e.preventDefault();const el=e.currentTarget,a=el.selectionStart,b=el.selectionEnd;setCode(code.slice(0,a)+'    '+code.slice(b));requestAnimationFrame(()=>{el.selectionStart=el.selectionEnd=a+4})}}}/><div className="editor-actions"><button className="text-link" disabled={busy} onClick={()=>{if(window.confirm('Replace this language’s code with the starter?'))setCode(starter(problem,language))}}>Reset</button><button className="secondary" disabled={busy||saving} onClick={()=>run(false)}><Play size={14}/>Run example</button><button className="primary" disabled={busy||saving} onClick={()=>run(true)}>{busy?'Running…':'Submit'}</button></div></div></div>
  <Tabs value={tab} onValueChange={setTab} className="run-tabs"><TabsList><TabsTrigger value="results">Test results</TabsTrigger><TabsTrigger value="history">Submission history</TabsTrigger></TabsList><TabsContent value="results"><div className="run-output" aria-live="polite">{runnerError&&<pre className="error-text compiler-error">{runnerError}</pre>}{busy?<p>Compiling and running {currentLanguage.name}…</p>:result?<><h3 className={result.passed===result.total?'green':'error-text'}>{result.passed===result.total?'All cases passed':'Some cases failed'} · {result.passed}/{result.total}</h3>{result.details.map((d,i)=><p key={i}>{d}</p>)}{result.diagnostics&&<details><summary>Compiler output</summary><pre className="compiler-error">{result.diagnostics}</pre></details>}</>:!runnerError&&<p>Run the example or submit against all {problem.tests.length} practice cases.</p>}</div></TabsContent><TabsContent value="history"><div className="run-output">{history.length?history.slice(0,20).map(s=><div className="submission-row" key={s.id}><span>{s.passed}/{s.total} passed · {languages.find(l=>l.id===(s.language||'javascript'))?.name}</span><span>{new Date(s.date).toLocaleString()}</span><button disabled={busy} className="text-link" onClick={()=>{choose(problem.id,s.language||'javascript');setCode(s.code)}}>Load code</button></div>):<p>No submissions yet.</p>}</div></TabsContent></Tabs>
  <p className="source-note">Runs send your code to <a href="https://wandbox.org" target="_blank" rel="noreferrer">Wandbox</a> for isolated execution. Submissions save to your account. Passing these practice cases does not guarantee correctness.</p>
 </>;
}
