'use client';
import {useEffect,useRef,useState} from 'react';
import PdfPreview from './pdf-preview';
import {Download,Play,Save} from 'lucide-react';
import {OutLink,type SavedState} from './workspace';
export default function ResumeStudio({state,save,saving}:{state:SavedState;save:(s:SavedState)=>Promise<boolean>;saving:boolean}){
 const [source,setSource]=useState(state.resumeSource||''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[log,setLog]=useState(''),[pdf,setPdf]=useState(''),[compiled,setCompiled]=useState('');
 const host=useRef<HTMLIFrameElement>(null),dirty=useRef(false),job=useRef<{id:string;source:string}|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{if(host.current?.contentDocument?.readyState==='complete')setReady(true)},[]);
 useEffect(()=>{if(!dirty.current&&state.resumeSource)setSource(state.resumeSource)},[state.resumeSource]);
 useEffect(()=>{const controller=new AbortController();if(!state.resumeSource)fetch('/templates/jakes-student.tex',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Template could not load.');return r.text()}).then(text=>{if(!dirty.current)setSource(current=>current||text)}).catch(e=>{if(e.name!=='AbortError')setError('Template could not load. Reload the page to retry.')});return()=>controller.abort()},[]);
 useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.source!==host.current?.contentWindow||event.origin!==location.origin||event.data?.type!=='resume-result'||event.data.id!==job.current?.id)return;const result=event.data;if(timer.current)clearTimeout(timer.current);setBusy(false);setLog(result.log||'');setError(result.error||'');if(result.pdf){setPdf(URL.createObjectURL(new Blob([result.pdf],{type:'application/pdf'})));setCompiled(job.current!.source)}job.current=null};addEventListener('message',receive);return()=>{removeEventListener('message',receive);if(timer.current)clearTimeout(timer.current)}},[]);
 useEffect(()=>()=>{if(pdf)URL.revokeObjectURL(pdf)},[pdf]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current&&source!==state.resumeSource){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',warn);return()=>removeEventListener('beforeunload',warn)},[source,state.resumeSource]);
 function compile(){if(!ready||busy||!source)return;const id=crypto.randomUUID();job.current={id,source};setBusy(true);setError('');host.current?.contentWindow?.postMessage({type:'compile-resume',id,source},location.origin);timer.current=setTimeout(()=>{setBusy(false);setError('The compiler did not respond. Reload the compiler and try again.');job.current=null;setReady(false);if(host.current)host.current.src='/vendor/latex/index.html?retry='+Date.now()},65000)}
 function downloadSource(){const url=URL.createObjectURL(new Blob([source],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='resume.tex';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <><div className="inline-links"><OutLink href="https://www.overleaf.com/latex/templates/jakes-resume/syzfjbzwjncs">Jake’s Resume template</OutLink><OutLink href="https://github.com/jakegut/resume">Source & license</OutLink></div>
 <div className="resume-actions"><button className="primary" onClick={compile} disabled={!ready||busy||!source}><Play size={15}/>{busy?'Compiling…':'Compile PDF'}</button><button className="secondary" disabled={saving||!source||source===state.resumeSource} onClick={async()=>{if(await save({...state,resumeSource:source}))dirty.current=false}}><Save size={15}/>{saving?'Saving…':'Save draft'}</button><button className="secondary" disabled={!source} onClick={downloadSource}><Download size={15}/>.tex</button>{pdf&&<a className="secondary" href={pdf} download="resume.pdf"><Download size={15}/>{source===compiled?'PDF':'Last compiled PDF'}</a>}<span role="status">{busy?'First compilation downloads TeX packages and may take a moment.':source===state.resumeSource&&source?'Draft saved':source?'Unsaved draft':''}</span></div>
 {error&&<div className="notice" role="alert">{error}</div>}
 <div className="latex-studio"><div className="latex-source"><div className="studio-label"><span>resume.tex</span><span>pdfLaTeX · {source.split('\n').length} lines</span></div><textarea aria-label="LaTeX resume source" value={source} spellCheck={false} maxLength={100000} onChange={e=>{dirty.current=true;setSource(e.target.value)}}/></div><div className="latex-preview"><div className="studio-label"><span>PDF preview</span><span>{pdf?(source===compiled?'Up to date':'Recompile to show edits'):'Compile to preview'}</span></div>{pdf?<PdfPreview url={pdf}/>:<div className="pdf-empty"><p>Compile PDF to preview your resume.</p></div>}</div></div>
 {log&&<details className="compile-log" open={!!error}><summary>Compiler log {error?'· fix the reported error':'· compilation complete'}</summary><pre>{log}</pre></details>}
 <details className="compact-details"><summary>LaTeX help & privacy</summary><div className="resume-help"><p><strong>Editing tip:</strong> Start after <code>\begin{'{document}'}</code>. Keep the braces around each field. Use <code>\&</code> for an ampersand and <code>\%</code> for a percentage.</p><p>Compilation runs in your browser; TeX packages are downloaded from TeXlyre. “Save draft” stores the source in your signed-in workspace. <a href="/vendor/latex/NOTICE.txt" target="_blank" rel="noreferrer">Compiler credits & source</a>.</p></div></details>
 <iframe ref={host} title="LaTeX compiler" src="/vendor/latex/index.html" hidden onLoad={()=>setReady(true)}/></>;
}
