'use client';
import ThemeToggle from './theme-toggle';
import {browserWorkspaceKey,readBrowserWorkspace,writeBrowserWorkspace,importBrowserWorkspace} from './browser-workspace';
import {type Planner,emptyPlanner} from './rutgers-courses';
import {useEffect,useState,useRef} from 'react';
import {ArrowUpRight,ArrowRight,BriefcaseBusiness,Code2,Layers3,BookOpen,GraduationCap,FileText,Plus,Search,Check,Trash2,Bookmark,LogOut,Terminal,PanelLeft,SlidersHorizontal,Users} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
import UniversityChooser from './university-chooser';
import {isUniversity} from './university';
import {type CampusPlan} from './campus-plan';

type Application={id:string;company:string;role:string;url:string;status:string;date:string;notes:string;employmentType?:string};
export type SavedState={interviews?:Record<string,import("./interview/exercise").InterviewProgress>;notebooks?:Record<string,import('./project-lab/notebook-course').NotebookProgress>;projectLabs?:Record<string,import('./project-lab/course').LabProgress>;planner:Planner;collegePlans:Record<string,CampusPlan>;applications:Application[];projects:string[];courses:string[];college:string;resumeSource:string;practiceSolved:string[];submissions:{id:string;problem:string;language?:'javascript'|'python'|'java'|'cpp';passed:number;total:number;code:string;date:string}[]};
export const freshState:SavedState={interviews:{},notebooks:{},projectLabs:{},planner:emptyPlanner,collegePlans:{},applications:[],projects:[],courses:[],college:'',resumeSource:'',practiceSolved:[],submissions:[]};
const nav=[['applications','My applications',BriefcaseBusiness],['opportunities','Open opportunities',Search],['projects','Project library',Layers3],['git-literacy','Git literacy',BookOpen],['resumes','Resume studio',FileText],['practice','Coding practice',Code2],['ai-interviews','AI interviews',Users],['courses','Course planner',GraduationCap],['clubs','CS clubs',Users]] as const;
const statuses=['Saved','Applied','Interviewing','Offer','Rejected'];
export function Picker({value,onChange,options,label,disabled=false}:{value:string;onChange:(v:string)=>void;options:string[];label:string;disabled?:boolean}){return <Select disabled={disabled} value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>}
export function OutLink({href,children}:{href:string;children:React.ReactNode}){return <a href={href} target="_blank" rel="noreferrer" className="out-link">{children}<ArrowUpRight size={15}/></a>}
export default function Workspace({section}:{section:string}){
 const [state,setState]=useState<SavedState>(freshState),[loading,setLoading]=useState(true),[user,setUser]=useState<{name:string;email:string}|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('All applications'),[employmentType,setEmploymentType]=useState('All types'),[edit,setEdit]=useState<Application|null>(null),[saving,setSaving]=useState(false);
 const [browserProgress,setBrowserProgress]=useState<SavedState|null>(null),[importing,setImporting]=useState(false);
 const stateRef=useRef(state);stateRef.current=state;
 const university=isUniversity(state.college)?universities[state.college]:null;
 const title=nav.find(n=>n[0]===section)?.[1]||'My applications';
 async function load(){setLoading(true);try{const r=await fetch('/api/state',{cache:'no-store'});const d=await r.json() as {error?:string;user:{name:string;email:string}|null;state:SavedState};if(!r.ok)throw Error(d.error||'Could not load your workspace.');setUser(d.user);if(d.user){setState({...freshState,...d.state});try{setBrowserProgress(readBrowserWorkspace(localStorage))}catch{toast.error('Browser progress could not be read. Your account is available.')}}else{setState(readBrowserWorkspace(localStorage)||freshState)}setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{document.title=(state.college||'CS Student Guide')+' · '+title},[state.college,title]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'get_workspace_progress',description:'Read counts of tracked applications, bookmarked projects, completed courses, and practice submissions in the current workspace.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty object.');const s=stateRef.current;return {applications:s.applications.length,savedProjects:s.projects.length,completedCourses:s.courses.length,submissions:s.submissions.length}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);

 async function save(next:SavedState){if(saving||loading||error){toast.error('Wait for your workspace to load, then retry.');return false;}setSaving(true);try{if(!user){writeBrowserWorkspace(localStorage,next);setState(next);toast.success('Saved in this browser');return true;}const r=await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});const d=await r.json() as {error?:string;user:{name:string;email:string}|null;state:SavedState};if(!r.ok)throw Error(d.error||'Could not save. Your changes are still here.');setState(next);toast.success('Saved to your workspace');return true}catch(e){toast.error((e as Error).message);return false}finally{setSaving(false)}}
 async function importProgress(){if(!browserProgress||importing)return;setImporting(true);try{if(await save(importBrowserWorkspace(browserProgress,state))){try{localStorage.removeItem(browserWorkspaceKey)}catch{}setBrowserProgress(null)}}finally{setImporting(false)}}
 const importNotice=browserProgress&&user?<div className="notice" role="status">Browser progress is available. Import adds saved items; existing account settings and resume take priority.<button disabled={saving||importing} onClick={importProgress}>{importing?'Importing…':'Import browser progress'}</button><button disabled={importing} onClick={()=>setBrowserProgress(null)}>Not now</button></div>:null;
 const add=(a?:Partial<Application>)=>setEdit({id:crypto.randomUUID(),company:'',role:'',url:'',status:'Saved',date:new Date().toISOString().slice(0,10),notes:'',employmentType:'Not specified',...a});
 const visible=state.applications.filter(a=>(filter==='All applications'||a.status===filter)&&(employmentType==='All types'||(a.employmentType||'Not specified')===employmentType)&&`${a.company} ${a.role}`.toLowerCase().includes(query.toLowerCase()));
 if(loading)return <main className="university-onboarding"><div role="status">Loading your workspace…</div></main>;
 if(error)return <main className="university-onboarding"><div className="notice" role="alert">{error} <button className="secondary" onClick={load}>Retry</button> <a href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/'+section)} target="_top">Sign in</a></div></main>;
 if(!university)return <>{importNotice}<UniversityChooser signedIn={!!user} saving={saving} onChoose={college=>save({...state,college})}/><Toaster theme="light" position="bottom-right"/></>;
 return <SidebarProvider><Sidebar className="side" collapsible="offcanvas"><SidebarHeader><a href="/" className="university-brand"><img src={university.logo} alt={university.name}/><span>{university.campus}</span></a><Picker disabled={saving} label="Selected university" value={state.college} options={Object.keys(universities)} onChange={college=>save({...state,college})}/></SidebarHeader><SidebarContent><div className="nav-label">WORKSPACE</div><SidebarMenu>{nav.map(([path,label,Icon],i)=><SidebarMenuItem key={path}>{i===2&&<div className="nav-label learn-label">LEARN & BUILD</div>}<SidebarMenuButton asChild isActive={section===path}><a href={'/'+path}><Icon size={18}/><span>{label}</span>{path==='applications'&&<span className="nav-count">{state.applications.length}</span>}</a></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="account"><span className="avatar">{user?.name?.slice(0,1).toUpperCase()||'F'}</span><div><strong>{user?.name||'Guest workspace'}</strong><small>{user?'Saved to your account':'Saved in this browser'}</small></div>{user?<a aria-label="Sign out" href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={16}/></a>:<a aria-label="Sign in to sync across devices" href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/'+section)} target="_top">Sign in</a>}</div></SidebarFooter></Sidebar><main className="main"><header className="topbar"><SidebarTrigger/><a href="/courses" className="university-masthead"><img src={university.logo} alt={university.name}/><span>{university.campus}</span></a><ThemeToggle/></header><div className="page">{importNotice}<div className="page-heading"><h1>{title}</h1><span className="workspace-theme"><ThemeToggle/></span>{section==='applications'&&<button className="primary" disabled={loading} onClick={()=>add()}><Plus size={17}/>Add application</button>}</div>{error&&<div className="notice" role="alert">{error} <button onClick={load}>Retry</button>{!user&&<a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT</a>}</div>}
 {section==='applications'?<><div className="stats">{[['Applications',state.applications.length],['In progress',state.applications.filter(a=>['Applied','Interviewing'].includes(a.status)).length],['Interviews',state.applications.filter(a=>a.status==='Interviewing').length],['Offers',state.applications.filter(a=>a.status==='Offer').length]].map(([label,num])=><div key={label}><div className="stat-label">{label}</div><strong className={label==='Offers'?'green':''}>{loading?'—':num}</strong></div>)}</div><div className="section-header"><a href="/opportunities" className="text-link">Explore opportunities <ArrowUpRight size={15}/></a></div><div className="toolbar"><div className="search"><Search size={17}/><input aria-label="Search applications" placeholder="Search company or role..." value={query} onChange={e=>setQuery(e.target.value)}/></div><Picker label="Filter application status" value={filter} onChange={setFilter} options={['All applications',...statuses]}/><Picker label="Filter employment type" value={employmentType} onChange={setEmploymentType} options={['All types','Internship','Full-time','Not specified']}/></div><div className="data-panel"><Table><TableHeader><TableRow><TableHead>COMPANY & ROLE</TableHead><TableHead>STATUS</TableHead><TableHead>DATE ADDED</TableHead><TableHead className="text-right">DETAILS</TableHead></TableRow></TableHeader><TableBody>{visible.map(a=><TableRow key={a.id}><TableCell><div className="company-cell"><span className="company-icon">{a.company.slice(0,2).toUpperCase()}</span><div><strong>{a.company}</strong><small>{a.role}{a.employmentType&&a.employmentType!=='Not specified'?` · ${a.employmentType}`:''}</small></div></div></TableCell><TableCell><span className={'status status-'+a.status.toLowerCase()}>{a.status}</span></TableCell><TableCell className="muted">{a.date}</TableCell><TableCell className="text-right"><button className="icon-button" aria-label={'Edit '+a.company+' application'} onClick={()=>setEdit(a)}><ArrowUpRight size={18}/></button></TableCell></TableRow>)}</TableBody></Table>{loading?<div className="loading-rows"><Skeleton className="h-12 w-full"/><Skeleton className="h-12 w-full"/></div>:!visible.length&&<Empty className="pipeline-empty"><EmptyHeader><EmptyTitle>{state.applications.length?'No matching applications':'No applications yet'}</EmptyTitle><EmptyDescription>{state.applications.length?'Try another search or filter.':'Add an application to start tracking.'}</EmptyDescription></EmptyHeader><button className="secondary" onClick={()=>add()}><Plus size={16}/>Add your first application</button></Empty>}</div></>:<Library section={section} state={state} save={save} add={add} saving={saving||loading||!!error}/>}
 </div></main><Dialog open={!!edit} onOpenChange={v=>{if(!v)setEdit(null)}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{state.applications.some(a=>a.id===edit?.id)?'Application details':'Add an application'}</DialogTitle><DialogDescription>Enter the role and its current status.</DialogDescription></DialogHeader>{edit&&<form onSubmit={async e=>{e.preventDefault();const next={...state,applications:state.applications.some(a=>a.id===edit.id)?state.applications.map(a=>a.id===edit.id?edit:a):[edit,...state.applications]};if(await save(next))setEdit(null)}}><label>Company<input required maxLength={120} value={edit.company} onChange={e=>setEdit({...edit,company:e.target.value})}/></label><label>Role<input required maxLength={180} value={edit.role} onChange={e=>setEdit({...edit,role:e.target.value})}/></label><label>Employment type<Picker label="Application employment type" value={edit.employmentType||'Not specified'} onChange={v=>setEdit({...edit,employmentType:v})} options={['Not specified','Internship','Full-time']}/></label><label>Application link<input type="url" placeholder="https://..." value={edit.url} onChange={e=>setEdit({...edit,url:e.target.value})}/></label><div className="form-grid"><label>Status<Picker label="Application status" value={edit.status} onChange={v=>setEdit({...edit,status:v})} options={statuses}/></label><label>Date added<input required type="date" value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value})}/></label></div><label>Notes & next steps<textarea rows={3} maxLength={3000} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})} placeholder="Recruiter contact, interview date, things to prepare..."/></label><div className="dialog-actions">{state.applications.some(a=>a.id===edit.id)&&<button disabled={saving} type="button" className="danger" onClick={async()=>{if(await save({...state,applications:state.applications.filter(a=>a.id!==edit.id)}))setEdit(null)}}><Trash2 size={16}/>Remove</button>}{edit.url&&/^https?:\/\//.test(edit.url)&&<OutLink href={edit.url}>View role</OutLink>}<button className="primary" disabled={saving}>{saving?'Saving…':'Save application'}</button></div></form>}</DialogContent></Dialog><Toaster theme="light" position="bottom-right"/></SidebarProvider>
}
import Library from './library';
import {universities} from './university';
