export type NotebookCell={id:string;source:string};
export type NotebookProgress={cells:NotebookCell[];completed:string[]};
export type NotebookOutput={kind:'file';name:string;base64:string}|{kind:'text';text:string}|{kind:'table';columns:string[];rows:string[][];total:number};
export const notebookId='campus-sales';
export const salesCSV=`order_id,day,item,category,units,unit_price
1,Mon,Coffee,Drinks,12,2.5
2,Mon,Latte,Drinks,8,4.5
3,Mon,Muffin,Food,6,3.0
3,Mon,Muffin,Food,6,3.0
4,Tue,Coffee,Drinks,,2.5
5,Tue,Sandwich,Food,7,6.0
6,Tue,Latte,Drinks,9,4.5
7,Wed,Muffin,Food,10,3.0
8,Wed,Sandwich,Food,5,6.0
9,Thu,Tea,Drinks,11,
10,Thu,Muffin,Food,-2,3.0
11,Fri,Coffee,Drinks,15,2.5
12,Fri,Latte,Drinks,10,4.5`;
export const notebookLessons=[
 {id:'load',title:'Load and inspect a CSV',goal:'Turn a small sales file into a pandas DataFrame.',body:'A DataFrame is a table with named columns and an index. Read the supplied CSV with pd.read_csv, then inspect its shape, types and first rows. This synthetic dataset includes a duplicate order, missing values and an invalid quantity for you to clean.',steps:['Run the cell to import pandas and NumPy and create df.','Change df.head() to df.tail() to see the last five orders.','Try print(df.shape) and df.dtypes. You should find 13 rows and 6 columns.'],hint:'Put an expression on the last line to display it. print() works anywhere. Run earlier cells before using variables they define.',starter:`import pandas as pd
import numpy as np
from io import StringIO

# Synthetic practice data, not real customer records.
csv_data = ${JSON.stringify(salesCSV)}
df = pd.read_csv(StringIO(csv_data))
df.head()`,solution:`import pandas as pd
import numpy as np
from io import StringIO

csv_data = ${JSON.stringify(salesCSV)}
df = pd.read_csv(StringIO(csv_data))
print(df.shape)
df.head()`,check:`assert isinstance(df, pd.DataFrame) and df.shape == (13, 6), "Read the supplied CSV into df (13 rows, 6 columns)."`,source:'https://pandas.pydata.org/docs/getting_started/intro_tutorials/02_read_write.html'},
 {id:'clean',title:'Clean the data',goal:'Build a trustworthy table before calculating anything.',body:'Missing quantities should contribute zero sales in this exercise. A missing price will use the median of known prices. These are explicit practice assumptions, not universal rules: real datasets need a justified policy. Remove duplicate order IDs and negative quantities.',steps:['Create clean with df.drop_duplicates(subset="order_id").copy().','Fill missing units with 0 and missing unit_price values with the column median.','Keep only rows where units >= 0. Use .copy() after filtering.','Show clean and confirm it has 11 rows and no missing numeric values.'],hint:'Assign back to the column: clean["units"] = clean["units"].fillna(0). A boolean mask inside clean[...] selects rows.',starter:"# Keep df unchanged; work on a new DataFrame.\nclean = df.drop_duplicates(subset=\"order_id\").copy()\n# TODO: fill missing values and remove negative quantities.\nclean",solution:"clean = df.drop_duplicates(subset=\"order_id\").copy()\nclean[\"units\"] = clean[\"units\"].fillna(0)\nclean[\"unit_price\"] = clean[\"unit_price\"].fillna(clean[\"unit_price\"].median())\nclean = clean[clean[\"units\"] >= 0].copy()\nclean",check:"assert len(clean) == 11 and clean[\"order_id\"].is_unique, \"Keep 11 unique valid orders.\"\nassert not clean[[\"units\", \"unit_price\"]].isna().any().any(), \"Fill both missing numeric values.\"\nassert (clean[\"units\"] >= 0).all(), \"Remove negative quantities.\"\nassert float(clean.loc[clean[\"order_id\"] == 4, \"units\"].iloc[0]) == 0, \"Use 0 for the missing quantity.\"\nassert float(clean.loc[clean[\"order_id\"] == 9, \"unit_price\"].iloc[0]) == 3, \"Use the median price (3.0) for the missing price.\"",source:'https://pandas.pydata.org/docs/user_guide/missing_data.html'},
 {id:'arrays',title:'Calculate with NumPy',goal:'Compute every order’s revenue without writing a loop.',body:'A NumPy array stores values for numerical work. Multiplication between equally shaped arrays works element by element. Convert both columns to arrays, multiply them, and assign the result as a new DataFrame column.',steps:['Create quantities = clean["units"].to_numpy() and prices = clean["unit_price"].to_numpy().','Compute revenue = quantities * prices. Each entry is units × price for one order.','Assign clean["revenue"] = revenue.','Calculate total_revenue = np.sum(revenue) and show it. The total is 342.00.'],hint:'Use np.round(total_revenue, 2) to format your result. Multiplying arrays is vectorized; you do not need a for loop.',starter:"quantities = clean[\"units\"].to_numpy()\nprices = clean[\"unit_price\"].to_numpy()\n# TODO: calculate revenue, add the column, and compute total_revenue.\nquantities",solution:"quantities = clean[\"units\"].to_numpy()\nprices = clean[\"unit_price\"].to_numpy()\nrevenue = quantities * prices\nclean[\"revenue\"] = revenue\ntotal_revenue = np.sum(revenue)\nprint(\"Revenue:\", np.round(total_revenue, 2))\nclean[[\"item\", \"units\", \"unit_price\", \"revenue\"]]",check:"assert isinstance(quantities, np.ndarray) and isinstance(prices, np.ndarray), \"Create NumPy arrays for quantities and prices.\"\nassert np.allclose(revenue, quantities * prices), \"Multiply the arrays element by element.\"\nassert np.allclose(clean[\"revenue\"], revenue), \"Add revenue to the clean DataFrame.\"\nassert np.isclose(total_revenue, 342.0), \"The total revenue should be 342.00 after cleaning.\"",source:'https://numpy.org/doc/stable/user/absolute_beginners.html'},
 {id:'filter',title:'Filter and rank orders',goal:'Find the largest drink orders.',body:'Combine boolean conditions with & and put each comparison in parentheses. Select the matching rows, sort them by revenue, and choose the columns you want to report.',steps:['Select rows where category == "Drinks" and revenue >= 35.','Sort by revenue in descending order and save the result as top_drinks.','Display order_id, item and revenue.','You should see order IDs 12, 6, 11 and 2, in that order.'],hint:'Use .sort_values("revenue", ascending=False). In pandas, use & rather than Python’s and to combine Series masks.',starter:"# TODO: filter clean and assign a sorted DataFrame to top_drinks.\n# top_drinks = ...\nclean[[\"order_id\", \"item\", \"category\", \"revenue\"]]",solution:"top_drinks = clean[(clean[\"category\"] == \"Drinks\") & (clean[\"revenue\"] >= 35)]\ntop_drinks = top_drinks.sort_values(\"revenue\", ascending=False)\ntop_drinks[[\"order_id\", \"item\", \"revenue\"]]",check:"assert isinstance(top_drinks, pd.DataFrame), \"Create top_drinks as a DataFrame.\"\nassert top_drinks[\"order_id\"].tolist() == [12, 6, 11, 2], \"Filter drinks with revenue >= 35, then sort largest first.\"",source:'https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html'},
 {id:'group',title:'Summarize by category',goal:'Turn individual orders into a sales report.',body:'groupby splits a table into groups, applies an operation to each group, and combines the results. Named aggregation makes it clear which columns you are summarizing.',steps:['Group clean by category.','Sum units into units_sold and revenue into revenue. Assign the summary to summary.','Compute summary["share_pct"] = 100 * summary["revenue"] / total_revenue.','Round the displayed summary to two decimal places. Drinks account for 222.00 and Food for 120.00.'],hint:'Use clean.groupby("category").agg(units_sold=("units", "sum"), revenue=("revenue", "sum")). The category becomes the index.',starter:"# TODO: group by category and create summary.\n# Then add each category’s percentage of total revenue.\nclean.groupby(\"category\")[\"units\"].sum()",solution:"summary = clean.groupby(\"category\").agg(\n    units_sold=(\"units\", \"sum\"),\n    revenue=(\"revenue\", \"sum\")\n)\nsummary[\"share_pct\"] = 100 * summary[\"revenue\"] / total_revenue\nsummary.round(2)",check:"assert np.isclose(summary.loc[\"Drinks\", \"revenue\"], 222.0), \"Drinks revenue should be 222.00.\"\nassert np.isclose(summary.loc[\"Food\", \"revenue\"], 120), \"Food revenue should be 120.00.\"\nassert np.isclose(summary[\"share_pct\"].sum(), 100), \"Category shares should sum to 100%.\"\nassert np.isclose(summary[\"units_sold\"].sum(), clean[\"units\"].sum()), \"Sum units_sold from the cleaned rows.\"",source:'https://pandas.pydata.org/docs/getting_started/intro_tutorials/06_calculate_statistics.html'},
 {id:'report',title:'Write your findings',goal:'Make the analysis understandable to someone who did not write it.',body:'A useful notebook pairs reproducible calculations with plain-language findings. Explain what you changed in the data and what the results can and cannot tell you. A tiny synthetic week of data cannot establish long-term demand.',steps:['Use summary["revenue"].idxmax() to find the top_category.','Print a short report that includes total revenue, the top category, and your missing-data assumptions.','Restart the kernel and Run all to confirm the notebook works from a clean session.','Download your .ipynb file to open it in Jupyter. Add a scratch cell to explore revenue by day.'],hint:'Run all executes top to bottom. If a later cell raises NameError, an earlier variable may never have been defined, or a previous cell failed.',starter:"top_category = summary[\"revenue\"].idxmax()\n# TODO: print the revenue total, top category and cleaning assumptions.\nprint(\"Top category:\", top_category)",solution:"top_category = summary[\"revenue\"].idxmax()\nprint(f\"Total revenue: ${total_revenue:.2f}\")\nprint(f\"Top category: {top_category}\")\nprint(\"Removed duplicate orders and negative quantities.\")\nprint(\"Missing quantities became 0; missing prices used the median.\")\nprint(\"This is a small synthetic sample, not a demand forecast.\")",check:"assert top_category == \"Drinks\", \"Find the category with the largest revenue using summary.\"\nassert np.isclose(total_revenue, 342.0), \"Run the calculation cells before writing the report.\"",source:'https://jupyter-notebook.readthedocs.io/en/stable/notebook.html'}
];
export function freshNotebook(lessons=notebookLessons):NotebookProgress{return {cells:lessons.map(l=>({id:l.id,source:l.starter})),completed:[]};}
export function exportNotebook(progress:NotebookProgress,lessons=notebookLessons){
 return {nbformat:4,nbformat_minor:5,metadata:{kernelspec:{display_name:'Python 3',language:'python',name:'python3'},language_info:{name:'python'}},cells:progress.cells.flatMap(c=>{const l=lessons.find(l=>l.id===c.id);return [...(l?[{id:c.id+'-lesson',cell_type:'markdown',metadata:{},source:`## ${l.title}\n\n${l.goal}\n\n${l.body}\n\n${l.steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}`}]:[]),{id:c.id,cell_type:'code',metadata:{},source:c.source,execution_count:null,outputs:[]}];})};
}

export type NotebookCourse={id:string;title:string;stack:string;filename:string;packages:string[];lessons:typeof notebookLessons};
export const salesCourse:NotebookCourse={id:notebookId,title:"Campus café sales",stack:"Python · pandas · NumPy",filename:"campus-cafe-sales.ipynb",packages:["numpy","pandas"],lessons:notebookLessons};
